### ISSUE TITLE
V12 release notes confusion

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#102]
In the V12 release notes you say that

- Removed ValueChangeEvent & ValueUpdateEvent

But these are still present (removed them anyway from my rules as I assume you intend to remove them), but `ValueNoUpdateEvent` has been removed and is not mentioned.

I replaced `ValueNoUpdateEvent` with `ItemNoUpdateEvent` using the new `Item.watch_update()` syntax.

I'm hoping this will work.

**Comment by spacemanspiff2007** [comment]
Sorry, I forgot the ``No``. I ment ``ValueNoChangeEvent`` & ``ValueNoUpdateEvent``.
Will fix this right away.
