### ISSUE TITLE
V12 Having a lot of trouble assigning Items to variables using get_item()

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#103]
I use this construct a lot:
```
        self.item = {}
        for item in self.watch_items:
            self.item[item] = Item.get_item(item)
            self.listen_event(self.item[item], self.update_received, ItemStateEvent)
```
where `self.watch_items` is a list of `Item` string names:
```
watch_items =  ['patiodoor_sensor',
                    'patio_door_position',
                    'patio_door_trigger',
                    'patio_door_online',
                    'patio_door_pet_toggle',
                    'gardenLight_fastonoff',
                    'patioDoorDoorContact',
                    'patiodoor_sensor_zwave_battery',
                    'patiodoor_sensor_zwave',
                    'patio_door_moving']
```
This looks like it should work (and is used in the examples), and worked in the past. Now i get this error:

```
2020-01-20 10:41:43,619[              HABApp.Rules]ERROR|                load: Could not load /etc/openhab2/HABApp/rules/patio_door.py: <class 'HABApp.core.items.item.Item'> != <class 'HABApp.openhab.items.contact_item.ContactItem'>!
2020-01-20 10:41:43,627[              HABApp.Rules]ERROR|                load:   File "/etc/openhab2/HABApp/rules/patio_door.py", line 40, in __init__
2020-01-20 10:41:43,628[              HABApp.Rules]ERROR|                load:     self.item[item] = Item.get_item(item)
2020-01-20 10:41:43,628[              HABApp.Rules]ERROR|                load:   File "/home/nick/Scripts/HABApp/HABApp/core/items/base_item.py", line 23, in get_item
2020-01-20 10:41:43,630[              HABApp.Rules]ERROR|                load:     assert isinstance(item, cls), f'{cls} != {type(item)}'
2020-01-20 10:41:43,633[              HABApp.Rules]ERROR|                load: AssertionError: <class 'HABApp.core.items.item.Item'> != <class 'HABApp.openhab.items.contact_item.ContactItem'>
```
This happens for all my rules where I use;
```
self.dict_name[item] = Item.get_item('name')
```
I have finally had to edit `HABApp/core/items/base_item.py` and `HABApp/core/items/item.py` to remove the line:
```
assert isinstance(item, cls), f'{cls} != {type(item)}'
```
as otherwise nothing will work, ie I can't assign an Item to a variable using `Item.get_item()`

How is this supposed to work? Am I supposed to use the class of Item, instead of `Item` to use `get_item` eg:
```
self.dict_name[item] = ContactItem.get_item('item_name')
```
Which would require knowing in advance the type of each item? This can't be right.

or do I use `BaseItem`? as `ContactItem` is a `BaseItem` type. But surely `ContactItem` is an `Item` also?

I have had to change a couple of `isinstance` tests where the test was against `HABApp.core.items.Item`, to `HABApp.core.items.base_item.BaseItem` as all items are a type `BaseItem` and not `Item`. This does not seem right.

What am I not understanding about these changes?

**Comment by spacemanspiff2007** [comment]
All items inherit from ``BaseItem``.
If it is a generic item with a value (e.g. not a Thing) use ``HABApp.core.BaseValueItem`` (this will work for habapp items and openhab items)
If it is an item from Openhab, use ``HABApp.openhab.items.OpenhabItem``.
If it is an item from HABApp use ``HABApp.core.items.Item.``

I'll see if I can include a inheritance graph in the documentation, then it'll be clear.

**Comment by NickWaterton** [comment]
This does not work well. `HABApp.core.BaseValueItem` does not have a method `get_create_item()`.

This is a major breaking change from previous versions - why make all these distinctions between OH and HABApp items?

I can get my rules working (without major editing) by adding
```
from HABApp.core.items.base_valueitem import BaseValueItem as Item
```
to my imports. Then I can find the instances of `Item.get_create_item()` and change them to a `SwitchItem` or something similar, as `BaseValueItem` does not have a `get_create_item()` method.

is there a reason for the assertion check?
```
assert isinstance(item, cls), f'{cls} != {type(item)}'
```
Without that everything works the same as it did before. Is there a reason why you can't just create a generic `Item` from an OH item - the final item will be of a specific type but does it matter? why not allow it? it would allow for much greater flexibility when assigning items from OH or HABapp.

I suggest removing this assertion check as not necessary, and allowing the use of generic `Item` when creating an OH/HABApp item.

**Comment by spacemanspiff2007** [comment]
> This does not work well. HABApp.core.BaseValueItem does not have a method get_create_item(). None of the Openhab items do.

This is intended because this does not create an item in openhab. Items from Openhab are automatically loaded on startup or when they are created so there should be no need for this class function.

> Then I can find the instances of Item.get_create_item() and try to change them to something else.

What do you mean by "change them to something else"?

> the final item will be of a specific type but does it matter?

Yes, because I have class specific converters which convert the events accordingly.

**Comment by NickWaterton** [comment]
I've updated my comments, but by "change them to something else" I meant `HABApp.core.items.Item.get_create_item()` as now `Item` maps to `BaseValueItem`.

When I ask if the final type matters, I mean does it matter if you create the item with a generic `Item` but it finally ends up as another type. I understand that afterwards it will be a `SwitchItem` or whatever, so that your class specific converters will function, but I don't see any difference between _creating_ the variable using generic `Item` vs `BaseValueItem`, except the first one doesn't work anymore the way it used to. The end result is the same, and `Item` inherits directly from `BaseValueItem` anyway.

It just seems like a restriction without a reason is what I'm saying.

**Comment by NickWaterton** [comment]
OK, I finally decided to bite the bullet, and I have replaced all my `Item.get_item()` entries with `OpenhabItem.get_item()` entries.

This solves the whole problem, but was quite the search and replace exercise throughout all my rules/files etc.

Hopefully I haven't missed anything.

As you say, probably could use some clarification in the documentation.

**Comment by spacemanspiff2007** [comment]
Sorry for the confusion. This was not intended to be a breaking change.
But the ``get_create_item`` caused some confusion in the forum and I believe this is a better solution in the long term.
