### ISSUE TITLE
Error in ColorItem

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#106]
I have been updating some `ColorItems`, and there is some confusion.

The first is that I have an rgb value that I need to send to a `ColorItem`. you provide the method `set_rgb`, however this does not update the `value` of the `ColorItem`, it just sets the `hue`, `saturation`, and `brightness` properties. Should this not update the `value` as well? otherwise the item h,s,v do not match the `value` h,s,v.

Anyway, looking at the code, `set_value` with the tuple `(None, None, None)` should update the `value` representation.

however, it doesn't because of some confusing code.
Here is the method:
```
    def set_value(self, hue=0.0, saturation=0.0, brightness=0.0):
        """Set the color value

        :param hue: hue (in °)
        :param saturation: saturation (in %)
        :param brightness: brightness (in %)
        """

        # map tuples to variables
        # when processing events instead of three values we get the tuple
        if isinstance(hue, tuple):
            hue, saturation, brightness = hue

        # with None we use the already set value
        self.hue = min(max(0.0, hue), HUE_FACTOR) if hue is not None else self.hue
        self.saturation = min(max(0.0, saturation), PERCENT_FACTOR) if saturation is not None else self.saturation
        self.brightness = min(max(0.0, brightness), PERCENT_FACTOR) if brightness is not None else self.brightness

        return super().set_value(new_value=(hue, saturation, brightness))
```
if you use `None` as any of the values then `value` gets updated with `None`, but the `ColorItem` property stays the same because of
`return super().set_value(new_value=(hue, saturation, brightness))` which doesn't use `self.hue` etc.

I'm not understanding this discrepancy between the `ColorItem` `hue`, `saturation`, and `brightness` properties, and the `value` representation. is there some reason for not keeping these in sync? Why update the `value` with `None` but leave the property as is?

It seems the only way to update a `ColorItem` with an RGB value is to do the following:
```
rgb = (0,255,0)    #green
item = OpenhabItem.get_item('color_item')
item.set_rgb(*rgb)
item.post_value(item.hue, item,saturation, item.brightness)
```
which then gives the error:
```
Traceback (most recent call last):
  File "/etc/openhab2/HABApp/rules/hsm200.py", line 90, in change_received
    self.set_color_from_number(event.value)
  File "/etc/openhab2/HABApp/rules/hsm200.py", line 129, in set_color_from_number
    self.set_color_from_name(color)
  File "/etc/openhab2/HABApp/rules/hsm200.py", line 140, in set_color_from_name
    self._item('HSM200_Color').post_value(hue, sat, bri)
  File "/home/nick/Scripts/HABApp/HABApp/openhab/items/color_item.py", line 54, in post_value
    super().post_value((hue, saturation, brightness))
  File "/home/nick/Scripts/HABApp/HABApp/core/items/base_valueitem.py", line 51, in post_value
    self.set_value(new_value)
  File "/home/nick/Scripts/HABApp/HABApp/openhab/items/color_item.py", line 41, in set_value
    self.hue = min(max(0.0, hue), HUE_FACTOR) if hue is not None else self.hue
TypeError: '>' not supported between instances of 'tuple' and 'float'
```
Because the Openhab `ColorItem` does not support the passing of a tuple..

So I think I have to use:
```
self.oh.send_command(item, (item.hue, item,saturation, item.brightness))
```
is this what is intended?
Thanks,

**Comment by spacemanspiff2007** [comment]
> I'm not understanding this discrepancy between the ColorItem hue, saturation, and brightness properties, and the value representation. is there some reason for not keeping these in sync? Why update the value with None but leave the property as is?

This is because this is a bug. :disappointed:
