### ISSUE TITLE
New Error in ColorItem

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#109]
I just updated to V12.1, and `ColorItem` still has some problems:

Here is the Item class:
```
class ColorItem(BaseValueItem):
    def __init__(self, name: str, hue=0.0, saturation=0.0, brightness=0.0):
        super().__init__(name=name, initial_value=(hue, saturation, brightness))

        self.hue: float = min(max(0.0, hue), HUE_FACTOR)
        self.saturation: float = min(max(0.0, saturation), PERCENT_FACTOR)
        self.brightness: float = min(max(0.0, brightness), PERCENT_FACTOR)

    def set_value(self, hue=0.0, saturation=0.0, brightness=0.0):
        """Set the color value

        :param hue: hue (in °)
        :param saturation: saturation (in %)
        :param brightness: brightness (in %)
        """

        # map tuples to variables
        # when processing events instead of three values we get the tuple
        if isinstance(hue, tuple):
            hue, saturation, brightness = hue

        # with None we use the already set value
        self.hue = min(max(0.0, hue), HUE_FACTOR) if hue is not None else self.hue
        self.saturation = min(max(0.0, saturation), PERCENT_FACTOR) if saturation is not None else self.saturation
        self.brightness = min(max(0.0, brightness), PERCENT_FACTOR) if brightness is not None else self.brightness

        return super().set_value(new_value=(self.hue, self.saturation, self.brightness))

    def post_value(self, hue=0.0, saturation=0.0, brightness=0.0):
        """Set a new value and post appropriate events on the event bus (``ValueUpdateEvent``, ``ValueChangeEvent``)

        :param hue: hue (in °)
        :param saturation: saturation (in %)
        :param brightness: brightness (in %)
        """
        super().post_value((hue, saturation, brightness))

    def get_rgb(self, max_rgb_value=255) -> typing.Tuple[int, int, int]:
        """Return a rgb equivalent of the color

        :param max_rgb_value: the max value for rgb, typically 255 (default) or 65.536
        :return: rgb tuple
        """
        r, g, b = colorsys.hsv_to_rgb(
            self.hue / HUE_FACTOR,
            self.saturation / PERCENT_FACTOR,
            self.brightness / PERCENT_FACTOR
        )
        return int(r * max_rgb_value), int(g * max_rgb_value), int(b * max_rgb_value)

    def set_rgb(self, r, g, b, max_rgb_value=255) -> 'ColorItem':
        """Set a rgb value

        :param r: red value
        :param g: green value
        :param b: blue value
        :param max_rgb_value: the max value for rgb, typically 255 (default) or 65.536
        :return: self
        """
        h, s, v = colorsys.rgb_to_hsv(r / max_rgb_value, g / max_rgb_value, b / max_rgb_value)
        self.hue = h * HUE_FACTOR
        self.saturation = s * PERCENT_FACTOR
        self.brightness = v * PERCENT_FACTOR
        self.set_value(None, None, None)
        return self

    def post_rgb(self, r, g, b, max_rgb_value=255) -> 'ColorItem':
        """Set a new rgb value and post appropriate events on the event bus (``ValueUpdateEvent``, ``ValueChangeEvent``)

        :param r: red value
        :param g: green value
        :param b: blue value
        :param max_rgb_value: the max value for rgb, typically 255 (default) or 65.536
        :return: self
        """
        self.set_rgb(r, g, b, max_rgb_value=max_rgb_value)
        self.post_value(None, None, None)

    def is_on(self) -> bool:
        """Return true if item is on"""
        return self.brightness > 0

    def is_off(self) -> bool:
        """Return true if item is off"""
        return self.brightness <= 0

    def __repr__(self):
        return f'<Color hue: {self.hue}°, saturation: {self.saturation}%, brightness: {self.brightness}%>'
```
I assume that `post_rgb()` is supposed to update the item, and post the h,s,i values to the Openhab item.

However while `post_rgb()` does set the values correctly, it does not post them, what it does is:
```
self.post_value(None, None, None)
```
which just post `None,None,None` to the OH item.

What I think it should be is:
```
    def post_value(self, hue=0.0, saturation=0.0, brightness=0.0):
        """Set a new value and post appropriate events on the event bus (``ValueUpdateEvent``, ``ValueChangeEvent``)

        :param hue: hue (in °)
        :param saturation: saturation (in %)
        :param brightness: brightness (in %)
        """
        self.set_value(hue, saturation, brightness)
        super().post_value((self.hue, self.saturation, self.brightness))
```
And `post_rgb()` should be:
```
    def post_rgb(self, r, g, b, max_rgb_value=255) -> 'ColorItem':
        """Set a new rgb value and post appropriate events on the event bus (``ValueUpdateEvent``, ``ValueChangeEvent``)

        :param r: red value
        :param g: green value
        :param b: blue value
        :param max_rgb_value: the max value for rgb, typically 255 (default) or 65.536
        :return: self
        """
        self.set_rgb(r, g, b, max_rgb_value=max_rgb_value)
        self.post_value(self.hue, self.saturation, self.brightness)
```
The reason you need `self.set_value(hue, saturation, brightness)` in `post_value(()`, is that otherwise if you just call `post_value(h,s,i)` the the values of `self.hue` etc never get updated, and again the item is out of sync with the actual OH item. You also need to send the actual values of `self.hue` etc, as sending `None` to the OH `BaseValueItem` will not work.

So I think this is just a simple oversight.

**Comment by spacemanspiff2007** [comment]
Just to be clear - none of these methods post anything to openhab.
It just posts the value to the (HABApp) internal event bus.
If you want to keep the oh item in sync you have to call 
```
item.set_rgb(1,2,3)
self.oh_post_update(item, item.value)
```

I am thinking of adding these methods to the openhab items but I am not there yet.
My main concern is confusion between HABApp and openhab methods and I have yet to come up with a clever naming scheme to prevent it.
If you have any ideas I'd gladly hear them.

That being said I will make changes to the part because it's hard to read and there is a bug which may trigger the ValueChangedEvent wrongly.

**Comment by NickWaterton** [comment]
Yes. of course - I was confusing `post_value()` and `post_update()`. As you say there is some confusion between Habapp methods and OH methods.

Thanks for clarifying.

**Comment by spacemanspiff2007** [comment]
I think ``send_command`` would be pretty obvious.
``post_update`` on the other hand can be easily confused with ``post_value``

I'd like to keep the words ``post`` and ``update`` so it's clear what's happening.
How about
- ``post_oh_update``
- ``oh_post_update``
- ``post_openhab_update``
- ``post_update_openhab``

What are your thoughts?

**Comment by NickWaterton** [comment]
I think that you should leave `send_command` and `post_update` as they are - as these are the same commands used in the OH rule engine, and it is clear that these are a one-to-one substitution. Alternatively you could go with `oh_send_command` and `oh_post_update`, but I don't fancy editing all my rules again...

The confusion comes between the OH event bus and the Habapp event bus. Most people are probably not using/are unaware of the Habapp event bus (as this does not exist in OH). They probably see no difference between the `value` of an item and the OH `state`. The confusion comes from the fact that you can change the `value` without changing the OH `state`.

triggering events withing Habapp, without triggering events in OH is not something most people would think of (this is a replacement rule engine for OH after all).

Perhaps the way to go is to change `set_value` and `post_value` to something more obvious (`ha_set_value`, `ha_post_value` maybe), as these are probably rarely used. I know I use them maybe 3 or 4 times, and only then because I didn't bother creating an OH item for something that is only used internally in Habapp (passing a sting between rules).

The added confusion comes when things like `post_rgb` are added - post where? send to OH? Hapabpp? you see the confusion.  You end up doing this:
```
item = OpenhabItem('colorItem_name')
item.set_rgb(255,0,0)
self.oh.send_command(item, item.value)
```
It's the `item.oh.send_command(item, item.value)` which is confusing, Maybe `self.oh.send_command_rgb(item, (r,g,b))` makes more sense (or `post_update_rgb`) for `ColorItems`.

Just my thoughts.

**Comment by spacemanspiff2007** [comment]
> I think that you should leave send_command and post_update as they are - as these are the same commands used in the OH rule engine, and it is clear that these are a one-to-one substitution. 

I am definitely leaving them as they are right now because they fit very good.

What I was talking about was wrapping openhab functions on openhab items:
````python
item = OpenhabItem('colorItem_name')
item.set_rgb(255,0,0)

item.send_command(item.value)  # openhab call
item.post_update(item.value)   # openhab call
# or
item.oh_send_command(item.value)  # openhab call
item.oh_post_update(item.value)   # openhab call
````

> The added confusion comes when things like post_rgb are added - post where? send to OH? Hapabpp? you see the confusion. You end up doing this:

How about ``post_rgb_value``? Then there is at least "value" in the name which can be used to create the analogy to ``post_value``?
