### ISSUE TITLE
Python error on rule load. TypeError: open_code() argument 'path' must be str, not PosixPath

### ISSUE THREAD

**Issue by sakhnevych** [spacemanspiff2007/HABApp#111]
I've created the first rule from here:
https://habapp.readthedocs.io/en/latest/getting_started.html

Got an error in logs:
> [2020-02-07 20:37:35,836] [             HABApp.Rules]    ERROR | Could not load /home/smartly/services/habapp/rules/test.py: open_code() argument 'path' must be str, not PosixPath!
> [2020-02-07 20:37:35,837] [             HABApp.Rules]    ERROR |   File "/usr/lib/python3.8/runpy.py", line 262, in run_path
> [2020-02-07 20:37:35,837] [             HABApp.Rules]    ERROR |     code, fname = _get_code_from_file(run_name, path_name)
> [2020-02-07 20:37:35,837] [             HABApp.Rules]    ERROR |   File "/usr/lib/python3.8/runpy.py", line 232, in _get_code_from_file
> [2020-02-07 20:37:35,838] [             HABApp.Rules]    ERROR |     with io.open_code(fname) as f:
> [2020-02-07 20:37:35,838] [             HABApp.Rules]    ERROR | TypeError: open_code() argument 'path' must be str, not PosixPath
> [2020-02-07 20:37:35,838] [             HABApp.Rules]  WARNING | Found no instances of HABApp.Rule in /home/smartly/services/habapp/rules/test.py

**Comment by spacemanspiff2007** [comment]
Hm - strange. It seems that python3.8 doesn't allow path like objects in ``runpy.run_path`` any more.
Would you be willing to test the current dev branch - I'll include a fix?

**Comment by spacemanspiff2007** [comment]
Does this fix your problem?

**Comment by sakhnevych** [comment]
Thank you for the quick response and fix!
Yes, sure.
I've tried to build locally but got the dependency issue with pyobjc-framework-Cocoa on Ubuntu.
I will fix it soon and test one more time.

From syslog:
> Feb 10 01:08:35 PinkBear systemd[1]: Started HABApp.
> Feb 10 01:08:35 PinkBear habapp[26058]: Traceback (most recent call last):
> Feb 10 01:08:35 PinkBear habapp[26058]:   File "/usr/local/bin/habapp", line 6, in <module>
> Feb 10 01:08:35 PinkBear habapp[26058]:     from pkg_resources import load_entry_point
> Feb 10 01:08:35 PinkBear habapp[26058]:   File "/home/smartly/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3253, in <module>
> Feb 10 01:08:35 PinkBear habapp[26058]:     def _initialize_master_working_set():
> Feb 10 01:08:35 PinkBear habapp[26058]:   File "/home/smartly/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3236, in _call_aside
> Feb 10 01:08:35 PinkBear habapp[26058]:     f(*args, **kwargs)
> Feb 10 01:08:35 PinkBear habapp[26058]:   File "/home/smartly/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3265, in _initialize_master_working_set
> Feb 10 01:08:35 PinkBear habapp[26058]:     working_set = WorkingSet._build_master()
> Feb 10 01:08:35 PinkBear habapp[26058]:   File "/home/smartly/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
> Feb 10 01:08:35 PinkBear habapp[26058]:     ws.require(__requires__)
> Feb 10 01:08:35 PinkBear habapp[26058]:   File "/home/smartly/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
> Feb 10 01:08:35 PinkBear habapp[26058]:     needed = self.resolve(parse_requirements(requirements))
> Feb 10 01:08:35 PinkBear habapp[26058]:   File "/home/smartly/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
> Feb 10 01:08:35 PinkBear habapp[26058]:     raise DistributionNotFound(req, requirers)
> Feb 10 01:08:35 PinkBear habapp[26058]: pkg_resources.DistributionNotFound: The 'pyobjc-framework-Cocoa>=4.2.2' distribution was not found and is required by watchdog

**Comment by spacemanspiff2007** [comment]
Just install watchdog 0.9.0, this will fix your issue and it will work
