### ISSUE TITLE
working with the OpenHAB rest/links/ endpoint

### ISSUE THREAD

**Issue by snpz** [spacemanspiff2007/HABApp#147]
Hi.

(I'm noidea from the OpenHAB community forum)

I have successfully implemented 3 methods now for this in http_connection and oh_interface:

``` python
async def async_add_link(self, item_name, thing_name, channel) -> bool:
async def async_link_exists(self, item_name, thing_name, channel) -> bool:
async def async_remove_link(self, item_name, thing_name, channel) -> bool:
```

They work fine as far as I can tell. What would be the best way to show you my changes? I cloned the repository to my pc and also created a new branch for the changes but I don't know how to create a Pull Request from the console now.
Do you have any idea how this works? Otherwhise I would probably need to create a fork first so I can use the Github UI for that.

(I'm mainly working alone with git til now. ;) )

**Comment by spacemanspiff2007** [comment]
Yes - do a fork into your personal repo (from the dev branch (!)) and add your changes there.
Then you can use the web-gui to create a pull request.

You can use tortoisegit or the github client to pull/push - I find it quite easier.
