### ISSUE TITLE
Deveop Branch error with getting groups OpenhabItemDefinition

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#148]
So I switched to the Deveop branch to checkout the weekday/weekend fix (which works by the way).

I now have a new error (that does not exist in the master branch).

This is the error:
```
2020-04-21 09:36:39,803[              HABApp.Rules]ERROR|            __exit__: Error "1 validation error for OpenhabItemDefinition
function -> params
  str type expected (type=type_error.str)" in load:
2020-04-21 09:36:39,804[              HABApp.Rules]ERROR|            __exit__: Could not load /etc/openhab2/HABApp/rules/garden_lights.py!
2020-04-21 09:36:39,805[              HABApp.Rules]ERROR|            __exit__: File "/usr/local/lib/python3.6/dist-packages/pydantic/main.py", line 338, in __init__
2020-04-21 09:36:39,805[              HABApp.Rules]ERROR|            __exit__:     raise validation_error
2020-04-21 09:36:39,806[              HABApp.Rules]ERROR|            __exit__: pydantic.error_wrappers.ValidationError: 1 validation error for OpenhabItemDefinition
2020-04-21 09:36:39,807[              HABApp.Rules]ERROR|            __exit__: function -> params
2020-04-21 09:36:39,807[              HABApp.Rules]ERROR|            __exit__:   str type expected (type=type_error.str)
```
it's pretty obscure, but I managed to track it down to this line in `garden_lights.py`
```
self.christmas_group = self.oh.get_item('gChristmas_Lights')
```
`gChristmas_Lights` is an OH group defined as:
```
Group:Switch:OR(ON, OFF) gChristmas_Lights "Christmas Lights" <christmas_tree> (ALL)
```
getting the data from the rest interface looks like this:
```
{
"members": [
{
"link": "http://192.168.100.119:8009/rest/items/christmasTree",
"state": "100",
"stateDescription": {
"minimum": 0,
"maximum": 100,
"step": 1,
"pattern": "%d%%",
"readOnly": false,
"options": []
},
"type": "Dimmer",
"name": "christmasTree",
"label": "Christmas Tree",
"category": "christmas_tree",
"tags": [],
"groupNames": [
"GF_Family",
"gChristmas_Lights",
"Lights",
"bedtime"
]
},
{
"link": "http://192.168.100.119:8009/rest/items/frontgardenPower",
"state": "OFF",
"stateDescription": {
"pattern": "%s",
"readOnly": false,
"options": []
},
"type": "Switch",
"name": "frontgardenPower",
"label": "Outside Power",
"category": "poweroutlet",
"tags": [],
"groupNames": [
"FrontGarden",
"Outlets",
"gChristmas_Lights",
"bedtime"
]
}
],
"groupType": "Switch",
"function": {
"name": "OR",
"params": [
"ON",
"OFF"
]
},
"link": "http://192.168.100.119:8009/rest/items/gChristmas_Lights",
"state": "ON",
"editable": false,
"type": "Group",
"name": "gChristmas_Lights",
"label": "Christmas Lights",
"category": "christmas_tree",
"tags": [],
"groupNames": [
"ALL"
]
}
```
Sorry about the indentation (it's just the way it copies from my browser).
I have other groups defined in other rules that work just fine, so there must be something different about this group definition (maybe the fact that the group is also defined as a switch?). There is no problem in the master branch, just Develop, so something has changed in `OpenhabItemDefinition` parsing.

I'll dig around see if I can figure out what it is.

**Comment by NickWaterton** [comment]
OK, found it.

It's in `HABApp/HABApp/openhab/definitions/rest/items.py ` the definition of `OpenhabItemDefinition` has this line:
```
group_function: Optional[Dict[str, str]] = Field(alias='function')
```
But in my group item this is:
```
"function": {
"name": "OR",
"params": [
"ON",
"OFF"
]
```
ie a string, and a list for `params`. So changing the definition of `OpenhabItemDefinition` to:
```
group_function: Optional[Dict[str, Union[str, list]]] = Field(alias='function')
```
Fixes the problem. This assumes that the parameters can only be a string or a list though.

**Comment by snpz** [comment]
I also looked it up in the documentation of the REST-Api which seems to be this:
https://www.eclipse.org/smarthome/documentation/javadoc/org/eclipse/smarthome/core/items/dto/GroupFunctionDTO.html#field.summary

params is defined as a string-array on GroupFunction DTO there.

**Comment by NickWaterton** [comment]
This is still a problem. I noticed several other group functions were not working. Investigating I found my homekit group definition:
```
Group:Switch homekit "Homekit Items [%s]" <house> (All)
```
json:
```
"groupType": "Switch",
"function": {
"name": "EQUALITY"
},
```

so `params` is missing. In fact it _is_ optional, the default function is "equals".

This change fixes it:
```
params: Optional[List[str]]
```

**Comment by snpz** [comment]
Thanks for clearing that up Nick. If anyone is interested - I found the [related method](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/items/dto/ItemDTOMapper.java#L106).
