### ISSUE TITLE
OpenHAB orphaned links after calling remove_item

### ISSUE THREAD

**Issue by snpz** [spacemanspiff2007/HABApp#150]
While playing around with the links-endpoint I noticed that, when deleting an item that has links, those links get not deleted automatically. I found [this post in the OpenHAB community forum](https://community.openhab.org/t/little-orphan-item/86785/6) describing the issue.

Would it be a good idea to delete all links automatically before deleting the item in remove_item to avoid this?
(this would require looping through all links though as there is no possibility to get only the links for a specific item)

**Comment by spacemanspiff2007** [comment]
Yes - it definately makes sense. I have already create ``ItemChannelLinkDefinition`` as an API-Object we can use

**Comment by snpz** [comment]
I looked at the definition - configuration is defined as ```Dict<str,str>``` but according to the [Configuration class](https://www.eclipse.org/smarthome/documentation/javadoc/org/eclipse/smarthome/config/core/Configuration.html) it is more a ```Dict<str,Any>```. (if Any in Python is comparable to Object in Java)

I think if we get the configuration from the Api we should also allow passing it when creating links and getting it via thing_get_link or something to be consistent. LinkNotFoundError would also come to mind.

Maybe we should continue the discussion in the Pull request?

**Comment by spacemanspiff2007** [comment]
I have created an issue in the openhab-core repository since this seems to be a bug.

**Comment by spacemanspiff2007** [comment]
How about we check for orphaned links once every startup of HABApp?
That way we can keep the registry clean without having to look up all channels on every item operation?
