### ISSUE TITLE
No unit separator found for dimensionless value

### ISSUE THREAD

**Issue by cputoaster** [spacemanspiff2007/HABApp#157]
connection to my OpenHAB 2.5.6 / HABApp 0.14.0 install:

```
Error No unit separator found for QuantityValue in "0.0" in map_items:
File "/home/habapp/habapp/lib/python3.8/site-packages/HABApp/openhab/map_items.py", line 29, in map_items
    14   def map_items(name, openhab_type: str, openhab_value: str) -> typing.Optional[BaseItem]:
 (...)
    25           if ':' in openhab_type:
    26               openhab_type = openhab_type[:openhab_type.find(':')]
    27               # if the item is not initialized its None and has no dimension
    28               if value is not None:
--> 29                   value, _ = QuantityValue.split_unit(value)
    30   
    ..................................................
     name = 'WeatherStation_UVLevel'
     openhab_type = 'Number'
     openhab_value = '0.0'
     typing.Optional = typing.Optional
     BaseItem = <class 'HABApp.core.items.base_item.BaseItem'>
     value = '0.0'
    ..................................................
```

Debugger breakpoint on line 25:
```
name = {str} 'WeatherStation_UVLevel'
openhab_type = {str} 'Number:Dimensionless'
openhab_value = {str} '0.0'
value = {str} '0.0'
```

**Comment by spacemanspiff2007** [comment]
Is there any reason you use ``Number:Dimensionless`` that prevents you from using ``Numer``?

**Comment by cputoaster** [comment]
As its officially available in the documentation, this means (to me) that the dimension is not unknown (like it would be by just being a Number) and I already checked it to be an actual dimensionless factor (eg a percentage or similar). I think its a nice and clean way to distinguish between a number that might or might not have a physical unit and a unit that is a dimensionless factor. And there seems to be other people thinking the same as it does exist in OpenHAB.

[https://www.openhab.org/docs/concepts/units-of-measurement.html](https://www.openhab.org/docs/concepts/units-of-measurement.html)

If you don't plan supporting this I could probably go through and de-assign the dimensions (and lose the information). But as I just tried HABApp for the first time it was also something that showed up as not being directly compatible with OpenHAB meaning it would get more difficult switching to and back from current Jython at least in a first phase.

Btw, just to be clear, I think HABApp is fantastic, especially when using IntelliJ remote debugging / editing via ssh.

**Comment by spacemanspiff2007** [comment]
Would you be willing to try the latest dev branch? I added support for ``Number:Dimensionless`` there.

> switching to and back from current Jython

You will probably switch and and never look back ;-)

It would also be nice if you could try the MultiModeItem and give me some feedback on it.
We could talk about it in the forum or wherever you like.

**Comment by cputoaster** [comment]
Will do once I am home... Thx!

**Comment by cputoaster** [comment]
Yes, seems to work fine! thanks!
