### ISSUE TITLE
Example Item code in documentation is invalid and should be updated

### ISSUE THREAD

**Issue by dafzor** [spacemanspiff2007/HABApp#161]
the documentation shows this example
```python
import HABApp
from HABApp.core.items import Item

class MyFirstRule(HABApp.Rule):
    def __init__(self):
        super().__init__()
        # Get the item or create it if it does not exist
        self.my_item = Item.get_create_item('Item_Name')

        self.run_soon(self.say_something)

    def say_something(self):
        # Post updates to the item through the internal event bus
        self.my_item.post_value('Test')
        self.my_item.post_value('Change')

        # The item value can be used in comparisons through this shortcut ...
        if self.my_item == 'Change':
            print('Item value is "Change"')
        # ... which is the same as this:
        if self.my_item.value == 'Change':
            print('Item.value is "Change"')


MyFirstRule()
```
Which gives an assertion:
`ERROR | AssertionError: <class 'HABApp.core.items.item.Item'> != <class 'HABApp.openhab.items.switch_item.SwitchItem'>`

Using `HABApp.openhab.items` of the specific item type works as expected.

Please update to a working example like [this one in the forum thread](https://community.openhab.org/t/habapp-easy-automation-with-openhab/59669/152).

**Comment by spacemanspiff2007** [comment]
Thanks for you feedback.
This example is intended to show how to create an Item that exists in HABApp only
which is useful to share states between rules/rule files.

How about I'll add the following to the example description:
```
This example will create an item in HABApp and post some updates to it.
To access items from openhab see the openhab item description.
```

**Comment by dafzor** [comment]
Wouldn't creating an item in happy be considered a more "advanced" use case?

Putting an example of "using openhab item" before, and relabeling the
habapp item one to "advance" would make it clear.

Would also help to clarify the use cases where having habapp items would be
useful.

**Comment by spacemanspiff2007** [comment]
I guess "advanced" is rather subjective. :wink: 
MultiModeItem and AggregationItem don't exist in oh at all and provide very useful logic.

I've changed the text a bit more and modified the examples.
Now it should be clear.

**Comment by dafzor** [comment]
I'm considering advanced from a habapp first contact.

First thing most people will want to do is port a openhab rule to try out
the system. Only then would they move on to habapp specific functionality,
no?
