### ISSUE TITLE
log times are not correct when using systemd logging

### ISSUE THREAD

**Issue by cputoaster** [spacemanspiff2007/HABApp#163]
This is probably more a question of understanding, but I would like to log some prints via standard systemd journal. Using the "print" command kind of works, but somehow the messages only appear later (maybe not flushed?), when restarting, all with a wrong (and same) timestamp. What is the recommended way? Not using "print" and only log.xx with a stream  : ext://sys.stdout logger? I basically looked at the examples and they seem to be using "print".

HABapp 0.15.1 / Ubuntu 20.04 LTS

```
Sep 11 06:46:37 shibuya systemd[1]: habapp.service: Succeeded.
Sep 11 06:46:37 shibuya systemd[1]: Stopped HABApp.
-- Reboot --
Sep 11 06:47:57 shibuya systemd[1]: Started HABApp.
Sep 14 08:52:44 shibuya systemd[1]: Stopping HABApp...
Sep 14 08:52:46 shibuya habapp[792]: SofasBulb8_Brightness changed from 0.0% to 100.0
Sep 14 08:52:46 shibuya habapp[792]: SofasBulb8_Brightness changed from 100.0% to 77.0
Sep 14 08:52:46 shibuya habapp[792]: SofasBulb8_Brightness changed from 77.0% to 100.0
Sep 14 08:52:46 shibuya habapp[792]: SofasBulb8_Brightness changed from 100.0% to 1.0
Sep 14 08:52:46 shibuya habapp[792]: SofasBulb8_Brightness changed from 1.0% to 0.0
Sep 14 08:52:46 shibuya habapp[792]: GarageDoor_Switch changed from OFF to ON
Sep 14 08:52:46 shibuya habapp[792]: GarageDoor_Switch changed from ON to OFF
Sep 14 08:52:46 shibuya habapp[792]: set_back
Sep 14 08:52:46 shibuya habapp[792]: Bamboo_Water changed from None to ON
Sep 14 08:52:46 shibuya habapp[792]: set_back
Sep 14 08:52:46 shibuya habapp[792]: Bamboo_Water changed from ON to OFF
Sep 14 08:52:46 shibuya habapp[792]: SofasBulb8_Brightness changed from 0.0% to 47.0
Sep 14 08:52:46 shibuya habapp[792]: SofasBulb8_Brightness changed from 47.0% to 0.0
```

**Comment by spacemanspiff2007** [comment]
I used print in the examples it is clear what is happening to the person looking at the examples.
If you don't receive the print, then I doubt you'll receive the ``sys.stdout`` logger.
Looking at my journal I seem to be getting the messages without delay.
How are you running HABApp?

Out of curiosity - why don't you use the suggested logging mechanism (e.g. event log, custom log file)?

**Comment by cputoaster** [comment]
Thanks for the quick reply. I am starting HABApp via systemd and using it to automate parts of an openHAB installation with around 150 bulbs / sensors / switches including a weather station, garden watering and under floor heating. It generates a lot of logs. I am currently experimenting as I prefer standard python 3 to the Jython I currently have all my scripts on.

Just out of simplicity I prefer only having one logging database and journalctl seems performant and easy to use with log alerting tools without having slow to grep files everywhere. Also, its just simpler to use one command with one way of finding logs ("journalctl -u habapp") than having to know where all the log files of all apps are written.

```
[Unit]
Description=HABApp
After=network-online.target

[Service]
Type=simple
User=habapp
Group=habapp
ExecStart=/home/habapp/habapp/bin/habapp -c /home/habapp/config

[Install]
WantedBy=multi-user.target
```

**Comment by spacemanspiff2007** [comment]
You can try to flush the buffer, maybe this helps:
https://www.systutorials.com/how-to-flush-stdout-buffer-in-python/

**Comment by spacemanspiff2007** [comment]
@cputoaster Have you figured it out?

**Comment by cputoaster** [comment]
Thanks a lot for asking. Actually, the print() does start working if I flush after doing a print. Thanks a lot for the tip!
