### ISSUE TITLE
DeprecationWarning:The loop argument is deprecated since Python 3.

### ISSUE THREAD

**Issue by mephlo** [spacemanspiff2007/HABApp#165]
With python 3.8.5 on a fedora 32 server I get this hints in my logs:

`/var/lib/openhab2/habapp/lib64/python3.8/site-packages/aiohttp/locks.py:21: DeprecationWarning:The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.`

**Comment by spacemanspiff2007** [comment]
Thank you for your issue. This seems to be a problem with an underlying library.
As soon as an update is available I'll include it in the setup.
