### ISSUE TITLE
self.run_on_every_day(datetime.time(0,0) triggers every second instead of at midnight

### ISSUE THREAD

**Issue by dobernhardt** [spacemanspiff2007/HABApp#174]
I had expect that a call self.run_on_every_day(datetime.time(0,0) would trigger everyday on midnight. Instead it fires every second.
Tested with 0.16.0

**Comment by spacemanspiff2007** [comment]
Would it be possible that you try the fix in the dev branch?
If you use a venv you can just replace the HABApp contents under ``lib/site-packages/HABApp`` with the sources from github.

**Comment by dobernhardt** [comment]
Tested with dev 16.1 and it works! Thanks.
