### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by nanosonde** [spacemanspiff2007/HABApp#19]
Hi!
Do you have any plans for a dockerized version of HABapp?

**Comment by spacemanspiff2007** [comment]
Yea - would be nice to try it out quickly. Should be relatively easy since it's just a package installation.
Currently I'm busy but I'll take a look at it in a couple of weeks.

**Comment by spacemanspiff2007** [comment]
Created Dockerfile with b09cfd6
