### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by spacemanspiff2007** [spacemanspiff2007/HABApp#194]
@loewexy
I added a small [overview](https://habapp.readthedocs.io/en/develop/about_habapp.html). Do you think this is helpful?
What are you missing?

**Comment by loewexy** [comment]
Yeah that is very nice and helpful.

I am missing how the coupling between the HABApp Openhab and HABApp MQTT items with Openhab and the MQTT Broker works. Is there an up to date cache fed by the Openhab Eventstream or does every access of the Item value trigger a REST call to Openhab, and similar for MQTT.

**Comment by spacemanspiff2007** [comment]
It's an item cache so performance is very good. Sending commands/updates or publishing stuff of course uses the corresponding API.
