### ISSUE TITLE
Generated .thing file only contains one entry from multi-entry config

### ISSUE THREAD

**Issue by Etzeitet** [spacemanspiff2007/HABApp#199]
When using multiple entries in a single `thing_<whatever>.yml`, the generated `.thing` text file only shows items generated from a single block. I initially thought it was the last defined block, but playing about their ordering doesn't affect what gets written to the `.thing` file. It could be the last item after the definitions are sorted, rather than definition order.

Regardless of order, only the things generated for the door sensor are written to the `.thing` file.

I am aware I could separate these out into different files, but for my use case I'd prefer to keep very similar items together (such as all z-wave switches regardless of vendor).

I suspect the file is being overwritten, rather than appended to, as HABApp processes each part of the config.

My thing definition:

```
- test: true

  filter:
    - thing_type: "zwave:aeon_zw112_00_000"

  channels:
    - filter:
        channel_type: zwave:sensor_door

      link items:
        - type: Contact
          name: "{thing_label}"
          label: "{thing_label}"
          icon: contact

    - filter:
        channel_type: "system:battery-level"


      link items:
        - type: Number
          name: "{thing_label}_Battery"
          label: "{thing_label} Battery"
          icon: battery

- test: true

  filter:
    - thing_type:  "zwave:aeon_zw116_02_001"

  channels:
    - filter:
        channel_uid: "zwave:switch_binary"

      link items:
        - type: Switch
          name: "{thing_label}_Switch"
          label: "{thing_label} Switch"
          icon: light
```

Which produces the `.thing` file:

```
Contact   Front_Door_Contact                "Front Door Contact"                    <contact> {channel = "zwave:device:154027fba8:node24:sensor_door"      }
Number    Front_Door_Contact_Battery        "Front Door Contact Battery"            <battery> {channel = "zwave:device:154027fba8:node24:battery-level"    }
```

**Comment by spacemanspiff2007** [comment]
Should be fixed in the dev branch, too

**Comment by Etzeitet** [comment]
Hello. I can confirm this is working as expected when running from the Develop branch.
