### ISSUE TITLE
Feature request: Integration with frontail

### ISSUE THREAD

**Issue by magnuslsjoberg** [spacemanspiff2007/HABApp#202]
I just upgraded openHABian and reinstalled HABApp with the new openHABian option. Very smooth!
I have all files version controlled by Git, so it was a 2 minute job.

Since HABApp now logs to the default openHAB log directory, I think it would make sense to integrate better with frontail.

Please add something like below to the openHABian HABApp installation scripts.

1. in `/etc/systemd/system/frontail.service`:
add `/var/log/openhab/HABApp.log` to `ExecStart=/usr/lib/node_modules/frontail/bin/frontail...`

2. In `/usr/lib/node_modules/frontail/preset/openhab.json`:
    add   `"/var/log/openhab/HABApp.log": "text-align: right; font-size: 0.8em; border-top: 2px solid #F8F8F8;",` in the `lines` section.

3. in `logging.yml` change log format:
```
formatters:
  HABApp_format:
    # format: '[%(asctime)s] [%(name)25s] %(levelname)8s | %(message)s'
    format: '%(asctime)s.%(msecs)03d [%(levelname)-5s] [%(name)-36s] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'  
```

4.  Somewhere (I put it in one of my rules files) add:
```
# Map WARNING to WARN to match openHAB logs
logging.addLevelName(logging.WARNING, 'WARN')
```

The frontail log viewer now integrates the HABApp log with the same look and highlighting as the other log entries:

```
2021-01-23 14:52:25.098 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Hue_Entrance_Sensor_Illuminance' changed from 1880.1824734902648 lx to 1555.2492479174666 lx
2021-01-23 14:52:29.521 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HABApp_Ping' changed from 38.1 to 39.2
2021-01-23 14:52:31.522 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Wallpanel_Charger' received command OFF
2021-01-23 14:52:31.529 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Wallpanel_Charger' predicted to become OFF
==> /var/log/openhab/HABApp.log <==
2021-01-23 14:52:31.458 [INFO ] [HABApp                              ] - WallPanel charger OFF, batteryLevel = 97
==> /var/log/openhab/events.log <==
2021-01-23 14:52:33.497 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'UPS_Load' changed from 13.0 to 12.0
2021-01-23 14:52:33.529 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'UPS_Input_Voltage' changed from 241.0 to 240.0
2021-01-23 14:52:39.549 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HABApp_Ping' changed from 39.2 to 38.8
2021-01-23 14:52:44.096 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Internet_Ping_Latency' changed from 52.0 to 48.0
2021-01-23 14:52:45.147 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Internet_Ping_Lastseen' changed from 2021-01-23T14:51:42.982+0100 to 2021-01-23T14:52:44.084+0100
2021-01-23 14:52:49.582 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'HABApp_Ping' changed from 38.8 to 41.2
```

**Comment by spacemanspiff2007** [comment]
I am currently a little bit swamped, but it would be nice if you could make a PR in openhabian.

**Comment by magnuslsjoberg** [comment]
I may try to do that if I manage to find a proper solution.

I guess there should be an additional log formatter that is automatically selected as default on openHABian.
That log formatter should probably map WARNING to WARN internally (somehow).

I will read up on logging formatters and see if I can write a PR for HABApp for that part!

Once that is in place, it makes sense to write (the simpler) PR for openHABian which 
addresses the actual integration with frontail.

No point making a half-baked solution that will get rejected...

I hope I can com back with the two PR:s needed in a not too distant future.

**Comment by spacemanspiff2007** [comment]
> I guess there should be an additional log formatter that is automatically selected as default on openHABian. That log formatter should probably map WARNING to WARN internally (somehow). I will read up on logging formatters and see if I can write a PR for HABApp for that part! Once that is in place, it makes sense to write (the simpler) PR for openHABian which addresses the actual integration with frontail.



I can do that and I already have platform logic in place. If you do the openhabian PR I'll do the changes in HABApp

**Comment by magnuslsjoberg** [comment]
Brilliant! 

I have hacked away with openhabian and now have install and removal functions (like habapp.bash and the other installers) that works but am a bit uncertain on how to proceed...

Since one can install and remove frontail and habapp in any order desired, the changes to frontail must take place regardless of installation or removal order. What I have done now is a "Install/remove HABApp-frontail log integration" script that needs to be run every time one of the two is installed or removed.  Very clunky!

The other option would be to add the same functionality both in the frontail installer and the habapp installer which is not really ideal either...

I will read up on openhabian and then ask the openhabian maintainers for directions.

**Comment by magnuslsjoberg** [comment]
I just updated my installation with your latest changes and it works perfectly well! Thanks a lot!

Now I just have to finish up the openhabian PR.

**Comment by magnuslsjoberg** [comment]
Since this is fixed in HABApp dev 20.1 and openhabian https://github.com/openhab/openhabian/pull/1458, I think this can be closed.

**Comment by spacemanspiff2007** [comment]
Hi @magnuslsjoberg , I've not yet merged it because I am not happy with the current implementation.
Especially changing the level to "WARN" instead of "WARNING" seems to be a lot more tricky than I thought.
Since I want to leave the user a choice there should be an option to "revert" this change.
I thought about making a new configuration option, but then I'd be overwriting the users logging config depending on that option which is not nice, either. Also spreading the information into two files is a headache.
I'll try to come up with something

**Comment by spacemanspiff2007** [comment]
I've created a new ``levels`` section in the ``logging.yml`` which is optional and can be used for this.
Would you mind testing the creation of the default logging file on your installation?

**Comment by magnuslsjoberg** [comment]
OK, I found it in the frontail branch and will test this week (hopefully tonight).
Thank you for helping out!

**Comment by magnuslsjoberg** [comment]
Seems, like I'm stuck on this one!  For the first version you did, I just merged the changes straight into the affected python files. In this case it seems like I have to reinstall HABApp from the frontail-branch. 
Unfortunately I don't understand how to do that!

Is there a way to point pip to the frontail-branch on GitHub, or should I use pip install --find-links or perhaps pip install --editable to point to a local package.

Is this local package then just the complete contents on GitHub in a directory or how does it work?  Any help appreciated!

**Comment by magnuslsjoberg** [comment]
Probably unstuck!!!  `pip install -e  git+https://github.com/spacemanspiff2007/HABApp@fronttail#egg=HABApp` seems to do the trick!

**Comment by magnuslsjoberg** [comment]
Work very well!  I don't know how openhab/frontail handles CRITICAL but otherwise it is perfect!

<img width="810" alt="habapp-frontail" src="https://user-images.githubusercontent.com/10720325/108596359-d452b700-7384-11eb-9dd5-eb7081394b3e.png">

**Comment by spacemanspiff2007** [comment]
Thanks for verifying!
