### ISSUE TITLE
Idea: flask server in HABApp???

### ISSUE THREAD

**Issue by magnuslsjoberg** [spacemanspiff2007/HABApp#203]
I have no clue if this is even possible, or if there would be any interest in it at all, but anyway...

For a wall panel, I have chosen to build a flask app instead of using HABpanel. I now have full freedom to do whatever I like using python, jinja, boostrap, angularjs or any other tools and framework I want.  In a way, that gives me the same freedom I felt with HABApp after struggling with DSL and JSR in openHAB.
 
The actual system works well and is very responsive but it currently means a lot of extra work to build the structures
and functions in the flask app. If I could connect the flask-app routes directly to HABApp rules, I could reuse all the logic and items I already built and also use HABApp functions to directly access items. 

HABApp has a very easy way of setting up listeners and then I could improve my setup by having a few customized event streams rather than using one single openHAB stream. I could also run more functions on the server rather than maintaining a third version of my setup, this time in JavaScript that communicates directly with the openHAB REST API.

The dream scenario would be that I could simply add routes and event stream handlers in HABApp and have no direct interaction with openHAB and minimal code in JavaScript.

Is this at all possible? (And if it is, would it fit into HABApp without bloating it completely?)

**Comment by spacemanspiff2007** [comment]
Imho you can try to start your flask app in the worker from the rule and try to work from there.
I don't know how this is performance wise but I guess it should be fine.

**Comment by spacemanspiff2007** [comment]
Just because I'm curious: Have you implemented the flask server together with HABApp?
I'm closing the issue but feel free to open again or create a new topic in the forums.

**Comment by magnuslsjoberg** [comment]
No, still running it as a service. Sharing some code between my HABApp rules and flask but currently it is working to well to motivate a rewrite.

I already have the code and only small changes in my setup so not too difficult to maintain a bit if duplicated code.

Please close!
