### ISSUE TITLE
Permission denied to access folders

### ISSUE THREAD

**Issue by Dilepa** [spacemanspiff2007/HABApp#204]
Hi,

I have installed habapp in a venv. It runs fine. when i try to execute subprocess command , it gives permission denied :
<ProcessInfo: returncode: -1, stdout: None, stderr: [Errno 13] Permission denied: '/home/dileepa/mycode'>

any hints?

**Comment by spacemanspiff2007** [comment]
You have to grant access to execute the file to the user you are running HABApp with.
Probably you don't have the "+x" flag set so the file can't be run (see chmod).

**Comment by Dilepa** [comment]
Thanks, I think that was the issue.
