### ISSUE TITLE
License Change to Apache 2.0

### ISSUE THREAD

**Issue by spacemanspiff2007** [spacemanspiff2007/HABApp#213]
Hey @Rosi2143 ,
I'd like to change the License to Apache 2.0 because it's a little bit more permissive.
Since you also contributed: is this okay with you?

**Comment by Rosi2143** [comment]
Hello @spacemanspiff2007,

no problem - making sharing and extending easy - is good.

Thanks for asking.

**Comment by spacemanspiff2007** [comment]
Switched license with 0.30.0
