### ISSUE TITLE
Feature request - sending cloud notifications via OpenHAB cloud

### ISSUE THREAD

**Issue by jenicek001** [spacemanspiff2007/HABApp#226]
Hello,
would it be possible to implement into HABApp functions sendNotification(), sendBroadcastNotification() and sendLogNotification(), which are available in OpoenHAB rules (via OpenHAB Cloud Connector)?
More details can be found here: https://www.openhab.org/docs/configuration/actions.html
Thank you,
Jan

**Comment by spacemanspiff2007** [comment]
Currently this is only possible through proxy items as described [here](https://habapp.readthedocs.io/en/latest/advanced_usage.html#invoking-openhab-actions).
I've created the [issue](https://github.com/openhab/openhab-core/issues/926) but unfortunately nobody worked on it yet.

**Comment by NickWaterton** [comment]
You can always use other python libraries to do the same thing though. I use prowl and e-mail from within HABApp to deliver notifications to my phone.

**Comment by alfista2600** [comment]
Not to pile on with alternative solutions, but we send messages of different priorities to different slack channels in a free account using python. All family members can get the alerts that they are looking for.

**Comment by spacemanspiff2007** [comment]
Thanks for all your input! I'm closing this because functionality is missing on the OpenHAB side.
