### ISSUE TITLE
OpenHAB 3 RESTapi delay with Basic auth

### ISSUE THREAD

**Issue by jenicek001** [spacemanspiff2007/HABApp#227]
Hello,
in my OpenHAB 3.0.1 on RaspberryPi 4 there is an average delay of 1000ms between RESTapi HTTP request and OpenHAB response. Same timing is also visible in HABApp_Ping. This is unfortunately making delay in reaction to events.

Let's demonstrate on following:

`time curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d 'OFF' "http://localhost:8080/rest/items/Light_bedroom_OnOff" -v -u user:password` - Basic Auth avg. delay of 1000ms

`time curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d 'OFF' "http://localhost:8080/rest/items/Light_bedroom_OnOff" -v` - works well without Basic Auth with delay 30-60ms

`time curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d 'OFF' "http://localhost:8080/rest/items/Light_bedroom_OnOff" -v -u oh.myAPItoken.wiAUkpSxgQD3rwrO6RneKVhzjLYxBWwoI417XjfXxDFIbvbDyfvsPT0SqMmika2RnPiUDQs9DEDFNfoBtg8MQg:''` - 
with generated OpenHAB API token - works well with delay 30-60ms

I have been looking on OpenHAB forums, but not found any solution for OH3 REST Basic Auth delay for similar config with pure localhost without nginx.

I see 2 possible options, would you please consider them for implementation?
- to (optionally) switch off Basic Auth in HABApp for commands which do not need it
- to implement OpenHAB API Token - see https://www.openhab.org/docs/configuration/apitokens.html . This option could be a config alternative to Basic Auth, token is sent via usename and there is no password at all, so should be simple to implement.

Thank you,
Jan

**Comment by spacemanspiff2007** [comment]
Have you read [this](https://habapp.readthedocs.io/en/latest/interface_openhab.html#additional-configuration)?

**Comment by jenicek001** [comment]
Hello, sure I read the HABApp manual for OpenHAB.
BTW - I tried to use the above shown authentication in HABApp - replaced a username in HABApp config by API Token and password by '' and it works also with OpenHAB 3.0 (and Release 3.1) with minimal response time.

**Comment by spacemanspiff2007** [comment]
Yes, it works. But basic auth with the auth cache introduced in 3.1 M3 is even faster.
