### ISSUE TITLE
Fast events trigger parallel calling of same callbacks

### ISSUE THREAD

**Issue by jenicek001** [spacemanspiff2007/HABApp#230]
In some cases MQTT (Zigbee2MQTT) sends duplicated messages with just few ms delay. This is causing parallel calling of same callback functions.
In general for any callbacks (regardless if called by scheduler or any Item event) it is very important to achieve their mutual exclusion and atomicity (within single Rule at least) - to avoid complicated user mutexes in most of rules.
In such case any time consuming calculations in user functions could be called async (or using run.soon scheduler).

**Comment by spacemanspiff2007** [comment]
I'm afraid I don't understand your issue. I get the duplicate messages thing but the rest is not clear.
You can already call any function as an async funtion.
Could you describe your issue further?

**Comment by jenicek001** [comment]
In more details - Zigbee2MQTT sends in my case 2 messages once an occupancy is detected. I setup a callback (MqttItem.get_create_item() and listen_event(). Due to extremly short time between 2 messages (~single ms), the callback is called twice and both callbacks are running parallel - so you can see in the log every debug message line twice from both callback invokes.
Problem is working with status variables (generally any shared resources) - first callback reads its value and before is able to react and write a new value, second callback is reading the original value and reacts the same way - so both callbacks e.g. calls cancel() to previously scheduled jobs (in my case at() or countdown() - this is how I discovered the problem - first callback calls run.countdown(), stored resulting CountdownJob, but second callback does the same - rewriting the CountdownJob variable, so later when you want to cancel() the CountdownJob - the first callback is ok (actually cancelling CountdownJob from previous second callback), but second callback cancel() raises JobAlreadyCancelled exception. BTW - first registered CountdownJob is still running. This is how I discovered it.
Of course I can protect access to any shared resources (like my variables) by mutex, however from my experience for event driven programming it makes much more sense to serialize it directly in the scheduler / events callbacks - of course this approach needs users to write a very short code in any callbacks.

**Comment by spacemanspiff2007** [comment]
Serializing is already possible if you write async code (see docs).
However you have to be careful to not block, otherwise you'll brake HABApp.

Serializing asynchronous tasks is no trivial problem and imho not necessary.
If you receive the same message two times in a row it looks like a mqtt subscription/publishing issue.
I'd rather investigate that.

**Comment by spacemanspiff2007** [comment]
This issue seems stale so I'm closing it.
Feel free to open again if you can reproduce the issue.
