### ISSUE TITLE
Enhancement: Better way to import modules/packages

### ISSUE THREAD

**Issue by dafzor** [spacemanspiff2007/HABApp#244]
Currently I have a series of helper classes for my rules. To import them i'm currently editing the PATH on the container deployment to be able to find my module in the rules folder.

Would you consider doing it for the default Dockerfile? Or even have a dedicated folder in `/config` for it?

**Comment by spacemanspiff2007** [comment]
Have you tried the ``lib`` entry in the [config](https://habapp.readthedocs.io/en/latest/configuration.html#configuration-contents)?
Does it not work as expected?

**Comment by dafzor** [comment]
Thanks, I searched the documentation but seems the content of the example config isn't indexed so never returned it when I searched for "module" or "package".

Created the lib folder and moved my helpers into it, and the rules load as normal.
