### ISSUE TITLE
Not Enough Threads?

### ISSUE THREAD

**Issue by alfista2600** [spacemanspiff2007/HABApp#267]
As I am moving more rules to HABApp, I'm starting to see more errors about scripts running long and suggesting that I don't have enough threads.

Is there a way to add more threads? Couldn't find anything...

Also, I do have some rules that take a couple seconds to run... could there be a way to set a rule to ignore the time warning?

```
2022-03-07 13:47:08.074 [WARN ] [HABApp.Worker                       ] - Starting of gMoistureMapper.change_color took too long: 2.88s. Maybe there are not enough threads?
2022-03-07 13:47:08.075 [WARN ] [HABApp.Worker                       ] - Starting of Homebridge_Integration.get_values took too long: 1.94s. Maybe there are not enough threads?
2022-03-07 13:47:08.076 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.17s. Maybe there are not enough threads?
2022-03-07 13:47:08.077 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.17s. Maybe there are not enough threads?
2022-03-07 13:47:08.079 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.17s. Maybe there are not enough threads?
2022-03-07 13:47:08.081 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.17s. Maybe there are not enough threads?
2022-03-07 13:47:08.082 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.17s. Maybe there are not enough threads?
2022-03-07 13:47:08.083 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.17s. Maybe there are not enough threads?
2022-03-07 13:47:08.085 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.18s. Maybe there are not enough threads?
2022-03-07 13:47:08.086 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.18s. Maybe there are not enough threads?
2022-03-07 13:47:08.087 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.18s. Maybe there are not enough threads?
2022-03-07 13:47:08.088 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.18s. Maybe there are not enough threads?
2022-03-07 13:47:08.092 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.18s. Maybe there are not enough threads?
2022-03-07 13:47:08.094 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.18s. Maybe there are not enough threads?
2022-03-07 13:47:08.096 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.19s. Maybe there are not enough threads?
2022-03-07 13:47:08.098 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.19s. Maybe there are not enough threads?
2022-03-07 13:47:08.099 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.19s. Maybe there are not enough threads?
2022-03-07 13:47:08.101 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.19s. Maybe there are not enough threads?
2022-03-07 13:47:08.102 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.19s. Maybe there are not enough threads?
2022-03-07 13:47:08.104 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.19s. Maybe there are not enough threads?
2022-03-07 13:47:08.104 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.19s. Maybe there are not enough threads?
2022-03-07 13:47:08.106 [WARN ] [HABApp.Worker                       ] - Starting of mqtt_to_portal.on_change took too long: 0.20s. Maybe there are not enough threads?
2022-03-07 16:05:25.034 [WARN ] [HABApp.Worker                       ] - Execution of Homebridge_Integration.get_values took too long: 18.90s
2022-03-07 16:05:25.065 [WARN ] [HABApp.Worker                       ] -    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
````

**Comment by NickWaterton** [comment]
Why are your rules taking so long to run? Are you running them asynchronously?

You shouldn't run synchronous commands in HabAPP that take too long to process - that's what the warning is for.

Could you post you rules that give the warning, maybe we can suggest improvements.

**Comment by alfista2600** [comment]
I haven't done anything with the async stuff mentioned in chapter 12.
The first rules I noticed with this were querying persistence information - taking about 2 seconds to run. I could probably rewrite this rule to not use persistence. It is monitoring power consumption to determine if certain appliances are running.
The mqtt_to_portal one simply posts to a MQTT topic whenever an item changes, but I think it is stuck on other jobs.
moisture_mapper can probably be run outside of HABApp. It periodically reads a number of moisture sensors and maps them to the corresponding houseplant they are assigned to.
The homebridge integration sometimes stalls and times out when it tries to get a new token from the server - this may be causing the hangup...
I just didn't know if there was something I could change to allow for more threads.

**Comment by NickWaterton** [comment]
You don't need more threads.

What I meant was that HabAPP is inherently asynchronous. If you do something that takes some time in a rule, you will get this warning. It's not really about threads.

Eg use synchronous packages like requests to access REST interfaces (HabAPP has an asynchronous alternative you should use), or waiting for results to return from some external source.

You need to use asynchronous versions of packages, or at least understand how to call synchronous methods from an asynchronous framework (without causing delays).

If you could post a rule that causes this warning, we may be able to help.

**Comment by alfista2600** [comment]
Thanks for the guidance. I remember with DSL rules threads was an issue.

Here is a rule that calls REST interface (homebridge). I can't figure out why it won't put all the code in a code block, sorry!
`
import HABApp
from HABApp.openhab.items import StringItem, SwitchItem
from HABApp.core.events import ValueUpdateEvent
import logging
import requests
import json
import datetime
import time

def string_to_command(argument):
    switcher = {
        "Cool": 2,
        "Fan": 1,
        "Off": 0,
        "Auto": 3
    }
    return switcher.get(argument, "nothing")

class Homebridge_Integration(HABApp.Rule):
    def __init__(self):
        self.authorization = ""
        super().__init__()
        self.listen_event('V_AC_Barn_Mode', self.on_change, ValueUpdateEvent)
        self.listen_event('V_AC_Barn_ModeSwitch', self.switch_to_string, ValueUpdateEvent)
        self.run.every_hour(
            callback=self.get_token
        )
        self.run.soon(
            callback=self.get_token
        )

    def get_token(self):
        url = 'http://192.168.0.XXX:8581/api/auth/login'
        payload = {'username': 'XXXXXXXX', 'otp': 'string', 'password': 'XXXXXXXX'}
        headers = {'content-type': 'application/json', 'accept': '*/*'}
        r = requests.post(url, data=json.dumps(payload), headers=headers)
        x = json.loads(r.text)
        self.authorization = str(x['access_token'])

    def on_change(self, event: ValueUpdateEvent):
        if SwitchItem.get_item('Setting_V_AC_Barn_Enabled') == 'ON':
            url = 'http://192.168.0.XXX:8581/api/accessories/'
            url = url + '117378f21f530239f2d5e4e6f3a54645365346345634505b75fa8538a0a5a92534704'
            headers = {'content-type': 'application/json', 'accept': '*/*', "authorization": "Bearer "
                                                                                             + self.authorization}
            payload = {
                "characteristicType": "TargetHeatingCoolingState",
                "value": string_to_command(event.value)
            }
            requests.put(url, data=json.dumps(payload), headers=headers)
            # log.warning(r.text)
        else: 
            log.warning('Barn AC Disabled So Ignored On Command')

log = logging.getLogger('MyRules')
Homebridge_Integration()
`

**Comment by NickWaterton** [comment]
The problem is:
```
r = requests.post(url, data=json.dumps(payload), headers=headers)
...
requests.put(url, data=json.dumps(payload), headers=headers)
```
These are synchronous calls, and so takes some time (hence the warning). You can't do this in an asynchronous framework.

This is what I do:
```
    def sendHttpGetRequest(self, url):
        self.run.soon(self._sendHttpGetRequest, url)
            
    async def _sendHttpGetRequest(self, url):
        try:
            async with self.async_http.get(url) as resp:
                self.response = await resp.json()
        except Exception as e:
            self.log.error('Error connecting to URL: {} : {}'.format(url, e))
```

It's described in https://habapp.readthedocs.io/en/latest/asyncio.html?highlight=self.async_http#HABApp.rule.interfaces.http.get

You can post, get whatever this way. The parameters are described in the aiohttp documentation, but it's similar to requests.

The key thing is that the response is `awaited`, which means other things can run while you are waiting for the response - so no delay, and no warnings.

I suspect your other warning messages have similar causes.

**Comment by alfista2600** [comment]
Thanks - I appreciate the example and give this a try!

**Comment by NickWaterton** [comment]
Here is your rule re-written try this:

```
import HABApp
from HABApp.openhab.items import StringItem, SwitchItem
from HABApp.core.events import ValueUpdateEvent
import logging
import requests
import json
import datetime
import time

def string_to_command(argument):
switcher = {
"Cool": 2,
"Fan": 1,
"Off": 0,
"Auto": 3
}
return switcher.get(argument, "nothing")

class Homebridge_Integration(HABApp.Rule):
    def init(self):
    self.authorization = ""
    super().init()
    self.listen_event('V_AC_Barn_Mode', self.on_change, ValueUpdateEvent)
    self.listen_event('V_AC_Barn_ModeSwitch', self.switch_to_string, ValueUpdateEvent)
    self.run.every_hour(self.get_token)
    self.run.soon(self.get_token)
        
    async def get_token(self):
        url = 'http://192.168.0.XXX:8581/api/auth/login'
        payload = {'username': 'XXXXXXXX', 'otp': 'string', 'password': 'XXXXXXXX'}
        headers = {'content-type': 'application/json', 'accept': '*/*'}
        async with self.async_http.post(url, json=payload, headers=headers) as resp:
            r = await resp.json()
            self.authorization = str(r['access_token'])

    def on_change(self, event: ValueUpdateEvent):
        self.run.soon(self._on_change, event)
    
    async def _on_change(self, event: ValueUpdateEvent):
        if SwitchItem.get_item('Setting_V_AC_Barn_Enabled') == 'ON':
            url = 'http://192.168.0.XXX:8581/api/accessories/'
            url = url + '117378f21f530239f2d5e4e6f3a54645365346345634505b75fa8538a0a5a92534704'
            headers = {'content-type': 'application/json', 'accept': '*/*', "authorization": "Bearer "
                                                                                             + self.authorization}
            payload = {
                "characteristicType": "TargetHeatingCoolingState",
                "value": string_to_command(event.value)
            }
            async with self.async_http.put(url, json=payload, headers=headers) as resp:
            r = await resp.text()
            # log.warning(r)
        else: 
            log.warning('Barn AC Disabled So Ignored On Command')

log = logging.getLogger('MyRules')
Homebridge_Integration()
```

**Comment by alfista2600** [comment]
awesome, thanks.... will implement it tonight.

**Comment by spacemanspiff2007** [comment]
Thank you @NickWaterton - your analysis was spot on!


@alfista2600 

The problem is that you do to much blocking stuff which takes time. HABApp then issues a warning that a new task is taking longer to start than expected. And you are doing a lot of stuff that every time takes some time (see the many log messages).
The perfect way to solve this is to use async functions. 
However you have to take special care that you don't do something blocking otherwise HABApp won't work at all during this time. These are some really hard to track down errors so take extra special care!

If you are new to asyncio I recommend you put the communication in an async rule and just use a proxy item.
Then you can write all your rules as normal


```python

# functions that create the payload as desired
def target_heating_cooling(value) -> dict:
    return {
        "characteristicType": "TargetHeatingCoolingState",
        "value": {"Cool": 2, "Fan": 1, "Off": 0, "Auto": 3}.get(value, "nothing")
    }


# Your ID definitions are now in a central place
IDS = {
    'BarnAC':
        ('117378f21f530239f2d5e4e6f3a54645365346345634505b75fa8538a0a5a92534704', target_heating_cooling)
}


class Homebridge_Integration(HABApp.Rule):
    def init(self):
        super().init()
        self.authorization = ""

        # This is the proxy item
        item = Item.get_create_item('HomebridgeCommand')
        item.listen_event(self.send_command, ValueUpdateEvent)

        self.run.every_hour(self.get_token)
        self.run.soon(self.get_token)

    async def get_token(self):
        url = 'http://192.168.0.XXX:8581/api/auth/login'
        payload = {'username': 'XXXXXXXX', 'otp': 'string', 'password': 'XXXXXXXX'}
        headers = {'content-type': 'application/json', 'accept': '*/*'}
        async with self.async_http.post(url, json=payload, headers=headers) as resp:
            r = await resp.json()
            self.authorization = str(r['access_token'])

    async def send_command(self, event: ValueUpdateEvent):

        # post a list/tuple with these three values to the item
        name, value = event.value
        homekit_id, homekit_payload_func = IDS[name]

        url = f'http://192.168.0.XXX:8581/api/accessories/{homekit_id}'
        headers = {
            'content-type': 'application/json', 
            'accept': '*/*', 
            "authorization": f"Bearer {self.authorization}"
        }

        async with self.async_http.put(url, json=homekit_payload_func(), headers=headers) as resp:
            if resp.status != 200:
                log.warning(await resp.text())


log = logging.getLogger('MyRules')
Homebridge_Integration()

```

from your other rules you then just call

```python
self.homebridge = Item.get_create_item('HomebridgeCommand')
self.homebridge.post_value('BarnAC', 'Cool')
```

The other rules don't have to be async rules so you can just write them as before!


> I can't figure out why it won't put all the code in a code block, sorry!

If you use tripple backticks it'll work as desired

**Comment by alfista2600** [comment]
Thanks again. I'm trying to get this going... some of it is over my head so taking baby steps.

Here is my current code (I know there are some extra imports - will use those later), and I have two issues:

```
import HABApp
from HABApp.core.items import Item
from HABApp.openhab.items import StringItem, SwitchItem
from HABApp.core.events import ValueUpdateEvent
import logging
import requests
import json
import datetime
import time


# functions that create the payload as desired
def target_heating_cooling(value) -> dict:
    return {
        "characteristicType": "TargetHeatingCoolingState",
        "value": {"Cool": 2, "Fan": 1, "Off": 0, "Auto": 3}.get(value, "nothing")
    }


IDS = {
    'BarnAC':
        ('117378f21f530239f2d5e4e6asdfasdfsdfadfasddsfasdfb75fa8538a0a5a92534704', target_heating_cooling)
}


class Homebridge_Integration(HABApp.Rule):
    def init(self):
        log.warning('starting')
        super().init()
        self.authorization = ""
        # This is the proxy item
        item = Item.get_create_item('HomebridgeCommand')
        item.listen_event(self.send_command, ValueUpdateEvent)

        self.run.every_hour(self.get_token)
        self.run.soon(self.get_token)

    async def get_token(self):
        log.warning('getting token')
        url = '192.168.0.XXX:8581/api/auth/login'
        payload = {'username': 'sadfsedf', 'otp': 'string', 'password': 'sdfasfd'}
        headers = {'content-type': 'application/json', 'accept': '*/*'}
        async with self.async_http.post(url, json=payload, headers=headers) as resp:
            r = await resp.json()
            self.authorization = str(r['access_token'])
            log.warning(self.authorization)

    async def send_command(self, event: ValueUpdateEvent):
        # post a list/tuple with these three values to the item
        name, value = event.value
        homekit_id, homekit_payload_func = IDS[name]

        url = f'192.168.0.XXX:8581/api/accessories/{homekit_id}'
        headers = {
            'content-type': 'application/json',
            'accept': '*/*',
            "authorization": f'Bearer {self.authorization}'
        }

        async with self.async_http.put(url, json=homekit_payload_func(), headers=headers) as resp:
            if resp.status != 200:
                log.warning(await resp.text())


log = logging.getLogger('MyRules')
log.warning('pre-starting')
Homebridge_Integration()
```

First, the log.warning('starting') never gets logged so I am unsure it is running. I use logging a lot for debugging (sad, I know)...
Second, PyCharm warns me about the 'self.authorization = "":
```
Reports a problem when instance attribute definition is outside __init__ method.
```

and I don't fully understand the implications of this warning but haven't been able to get it to go away in a way that I trust modifying your code suggestions.

**Comment by NickWaterton** [comment]
That's because you have written:
```
class Homebridge_Integration(HABApp.Rule):
    def init(self):
```
But it's supposed to be:
```
class Homebridge_Integration(HABApp.Rule):
    def __init__(self):
```
Notice the double `_` either side of `init`. That's what the error message is trying to tell you. `init(self)` is just a regular method, `__init__(self)` is what is run when the class is instantiated, and you don't have one.

**Comment by alfista2600** [comment]
Thanks! It was a good educational error for me... I learned a lot from this, uh, thread...Thanks for the support and patience!

**Comment by alfista2600** [comment]
and I think I needed to change this too? Getting some other errors in the actual code too but I'll work on those later...

```
        super().__init__() 
```

**Comment by alfista2600** [comment]
the next error, if anyone stumbles on this post, is that the URL's in the code need the HTTP prefix.

```
        url = 'http://192.168.0.XXX:8581/api/auth/login'
```

**Comment by NickWaterton** [comment]
Yes `super().__init__()` is correct (don't know what happened there), and yes, you need the prefix.
