### ISSUE TITLE
ItemCommandEvent value of item is incorrect

### ISSUE THREAD

**Issue by DerOetzi** [spacemanspiff2007/HABApp#270]
I have a switch which is NULL by default and is triggering a function where ON = OK and OFF = Not OK from the business logic.

The rule function looks like this:

```python


    def train(self, event: ItemCommandEvent):

        train_item = SwitchItem.get_item(event.name)
        self.log.info(train_item.is_on())
        train = train_item.is_on()

        # Logic here

        train_item.oh_post_update('NULL')

```

 train = train_item.is_on() and although  train = train_item.is_off() is always evaluated to False. It looks to me like the item is not updated on ItemCommandEvent

**Comment by spacemanspiff2007** [comment]
It's because the ``ItemCommandEvent`` does not update the item state and never has.
You have to trigger on ``ItemStateEvent`` or ``ValueUpdateEvent`` if you want the state update.
ItemCommandEvent is the outgoing command to the item/device.
ItemStateEvent is the incoming update from the item/device.

**Comment by DerOetzi** [comment]
Sorry can you explain your suggestion a little bit more, maybe with an example.

I have a GUI-Switch which is NULL by default. And user can choose "Correct" (ON) or "Incorrect" (OFF). On selection the rule should be triggered and reset the Switch to NULL. What is your suggestion to gain this target?

**Comment by spacemanspiff2007** [comment]
Combine an item with autoupdate false and use a mapping to create two buttons "Correct" "Incorrect".
```
Switch my_item {autoupdate="false"}
```

Then you can listen to the ItemCommandEvent and just compare it to ``ON`` and ``OFF``
