### ISSUE TITLE
Update label, category etc of an existing OH Item

### ISSUE THREAD

**Issue by DerOetzi** [spacemanspiff2007/HABApp#271]
In jython rules I can use setLabel or setCategory to update an item from rules.

Are some equivalent methods in HABApp?

**Comment by spacemanspiff2007** [comment]
[self.oh.create_item](https://habapp.readthedocs.io/en/latest/interface_openhab.html#HABApp.openhab.interface.create_item)

**Comment by DerOetzi** [comment]
I have seen this in the documentation, but on this function I have to give more then only the own label for example the oh item type  to only set a new label or only a category.

Thought about a wrapper function 

```python
my_item.set_label('New label')
```

**Comment by spacemanspiff2007** [comment]
You can build it your own but the item is in each case effectively removed and added to the oh item registry.
It's not a normal use case as the item should be somewhat static. Better use two items and combine them e.g. in the new gui.
