### ISSUE TITLE
Possible to deactivate openHAB connection (and some other wishes)?

### ISSUE THREAD

**Issue by cheak1974** [spacemanspiff2007/HABApp#290]
Hi,

this is a great project for simple implementation of rules in a MQTT based Smarthome environment.
I use only dockerized mosquitto and nodered for the entire smarthome. Everything is mapped to MQTT topics with help of nodered which is really good to maintain and absolutely stable and technology agnostic.

But I don't like to write rules in nodered because the "only one value at a time" paradigm gets in my way and makes even simple rules very complicated. For running rules on the MQTT landscape your tool is brilliant. I can just hook it in with almost no further dependencies and the dockerized solution is also great for my purposes.

From my side I would like to see some minor functions / improvement:

It would be great if there would be a switch to stop habapp trying to connect to openHAB. I personally do not use openHAB at all so the log file is spammed with messages complaining about a missing connection to openHAB. I would love to have a "clean" HABapp.log where I can see when "real" errors occur.

For the rule folder it would be great if rules with a leading underscored in the file name would be skipped (not imported) while loading. By doing this you could handle a lot of rules which are even still in development or maybe actually not used (maybe christmas lighting timers). So you could keep all your ready rules in the rule folder and deactivate it by just renaming it from "my_rule.py" to "_my_rule.py". 

During the tests I was not able to log to "HABApp.log" or "events.log". Maybe I am not experienced enough but maybe you could also make a "user.log" file which can be simply imported in the rules in order to log things for debugging in a separate file where only the user is logging to.

Maybe you could consider to implement some (or all) feature requests.

Keep up the great work!

best regards from germany

Chris

**Comment by spacemanspiff2007** [comment]
> It would be great if there would be a switch to stop habapp trying to connect to openHAB.

Just enter an empty value for the host. Then there will be no openhab connection.

> So you could keep all your ready rules in the rule folder and deactivate it by just renaming it from "my_rule.py" to "_my_rule.py".

Just rename ``my_rule.py_`` (tailing underscore)

> Maybe I am not experienced enough but maybe you could also make a "user.log" file which can be simply imported in the rules in order to log things for debugging in a separate file where only the user is logging to.

Something like this should work. I think there is also an example in the docs.
```python
log = logging.getLogger('HABApp')
log.info('Test')
```

**Comment by cheak1974** [comment]
Hi,
unfortunately this isn't working.

If I use 
`host = `
or
`host = ''`

habapp complains that it is expecting a string value in host because it is needed for a dictionary.

ile "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping

    raise er.MultipleInvalid(errors)

---- (full traceback above) ----

File "/usr/local/lib/python3.8/site-packages/HABApp/runtime/runtime.py", line 40, in start

    self.config_loader = HABApp.config.HABAppConfigLoader(config_folder)

File "/usr/local/lib/python3.8/site-packages/HABApp/config/config_loader.py", line 66, in __init__

    self.load_cfg()

File "/usr/local/lib/python3.8/site-packages/HABApp/config/config_loader.py", line 97, in load_cfg

    CONFIG.load(self.file_conf_habapp)

File "/usr/local/lib/python3.8/site-packages/EasyCo/config_file.py", line 63, in load

    validated_cfg = schema(cfg)

File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping

    raise er.MultipleInvalid(errors)


MultipleInvalid: expected str for dictionary value @ data['openhab']['connection']['host']

Executing <Task pending name='Task-1' coro=<Runtime.start() running at /usr/local/lib/python3.8/site-packages/HABApp/runtime/runtime.py:70> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe0a60cbe20>()] created at /usr/local/lib/python3.8/asyncio/base_events.py:422> created at /usr/local/lib/python3.8/site-packages/HABApp/__main__.py:81> took 0.156 seconds

Executing <Task pending name='Task-2' coro=<_shutdown() running at /usr/local/lib/python3.8/site-packages/HABApp/runtime/shutdown.py:59> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe0a6b470a0>()] created at /usr/local/lib/python3.8/asyncio/base_events.py:422> cb=[_chain_future.<locals>._call_set_state() at /usr/local/lib/python3.8/asyncio/futures.py:367] created at /usr/local/lib/python3.8/asyncio/tasks.py:922> took 0.796 seconds

**Comment by spacemanspiff2007** [comment]
> Is it possible to get this working with an error during start?

Have you tried an empty string? e.g. ''

**Comment by cheak1974** [comment]
Yes, I tried it completely empty, with two single quotes and with two double quotes.
Unfortunately the result is always the same.


regards

Chris

**Comment by spacemanspiff2007** [comment]
It should work now with 1.0. Can you check?

**Comment by spacemanspiff2007** [comment]
Ping @cheak1974

**Comment by spacemanspiff2007** [comment]
@cheak1974 
It should work now with 1.0. Can you check?

**Comment by spacemanspiff2007** [comment]
Closed since this issue seems to be stale
