### ISSUE TITLE
OpenHABian 1.7.4 & HABApp 1.0.1

### ISSUE THREAD

**Issue by alfista2600** [spacemanspiff2007/HABApp#303]
Finally trying to get around to testing/installing and spun up a Pi with current OpenHABian and then installed HABApp through the openhabian-config tool. Didn't receive any errors but at launch, HABApp reported that the 'astral' package was missing. Easily installed, but figured I'd report.

`Error: 1 package is missing:
 - eascheduler: No module named 'astral'
(habapp) openhabian@pi-openhab3:/opt/habapp $ pip install astral
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting astral
  Downloading https://www.piwheels.org/simple/astral/astral-2.2-py2.py3-none-any.whl (30 kB)
Collecting pytz
  Downloading https://www.piwheels.org/simple/pytz/pytz-2022.1-py3-none-any.whl (511 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.2/511.2 kB 1.2 MB/s eta 0:00:00`

**Comment by spacemanspiff2007** [comment]
Should be fixed with 1.0.2.
Could you please verify?

**Comment by alfista2600** [comment]
Verified! Thanks!
