### ISSUE TITLE
Add more info for MQTT Connection problems

### ISSUE THREAD

**Issue by swedchef** [spacemanspiff2007/HABApp#308]
Hi - what a great piece of software you have made here - i never liked the built-in rule-engine in openhab (probably because i think it lacks documentation), but here is a really nice python rule handler - and it's FAST!

Oh - i digress - sorry. The issue i had, was when i was trying to connect to MQTT i had little log information about what was happening. Just a message it was connecting, and then nothing more. Apparently i made the error of setting "tls" true, but i had actually not enabled it on the MQTT broker. I was totally in the blind. Perhaps future users would benefit from some sort of logging message on that? It seemed it just went "blank" and after a long time gave some warning that connection was still open.

Another thing - related to this - i spotted, was that when connecting multiple hosts with the same ID, HABApp will just continuously open and close the connection. Perhaps some logging here would help as well?

My use-case was - trying to identify what was wrong related to the first connection not working (tls = true) - i had connected a second HABApp instance that used the same id, and thereby mosquitto rejected the connection (it would seem).

Hope you can use this information to make a brilliant piece of software just a little better.

**Comment by spacemanspiff2007** [comment]
I've included a log output in 1.0.3 and the ClientID should be created unique by default.
