### ISSUE TITLE
Question about rule instantiation

### ISSUE THREAD

**Issue by nanosonde** [spacemanspiff2007/HABApp#31]
Hi!

What does this line in the example actually do?
https://github.com/spacemanspiff2007/HABApp/blob/d9e25cc9fe5ba4c56c809f6fb62bb52c4403736d/conf/rules/time_rule.py#L36

Is the rule really active?

**Comment by spacemanspiff2007** [comment]
yes, the rule will be active. You can observe that it'll be loaded in the logfile.
Instantiation however is enough:
```python
MyRule() 
```

**Comment by nanosonde** [comment]
Ok. So what can the assignment of the MyRule to the variable "a" be useful for?

**Comment by spacemanspiff2007** [comment]
Nothing in this case - I already have changed in the dev branch.
If you have more rules in one file you can call the respective group functions from the other class however
e.g.
```python
class B:
    def __init__(self):
       a.do_some_stuff()
B()
```

**Comment by nanosonde** [comment]
Ah, ok. Thanks!
