### ISSUE TITLE
Timezone settings for main log and events

### ISSUE THREAD

**Issue by nanosonde** [spacemanspiff2007/HABApp#34]
Hi!

The timestamps of the main log (HABApp.log) seems to use UTC, correct?
Is there a possibility to specify a timezone for this? I am in CEST (+0200) right now.

What does the current (only?) timezone setting in openhab->general do exactly?
Does it modify values from DateTime items or is it used for modifying the event log timestamps?

**Comment by spacemanspiff2007** [comment]
Logging should use your system locale (not UTC).
You have to set the Timezone in the environment variables for you docker container.
I just saw that alpine hasn't support for the TZ environment variable by default, so I will be updating the dockerfile.

> What does the current (only?) timezone setting in openhab->general do exactly?

This was a quick and dirty way to specify a timezone (e.g. ```+2000```) which is mandatory when posting timestamps to openhab

**Comment by spacemanspiff2007** [comment]
the parameter is no longer required as of 0.4.6.
Please remove it from the file.

**Comment by nanosonde** [comment]
Ok. Removed.

After setting TZ=Europe/Berlin in my docker env, the timestamps in the logs show the correct time now.
Should be put in the docs. ;-)
