### ISSUE TITLE
pre-1.0.0 images no longer available in dockerhub

### ISSUE THREAD

**Issue by dafzor** [spacemanspiff2007/HABApp#367]
Pre-1.0.0 images have been removed from dockerhub.

My setup is still running on openhab 2.5 thus i can't upgrade past v0.31.2, with the removal of the tag habApp failed migrate/restart during maintenance.

I've already resolved it by pushing a v0.31.2 build into my private registry, however I'd like to suggest keeping older tags in the future as people's setups might depend on them.

**Comment by spacemanspiff2007** [comment]
I'm sorry for the inconvenience. I went through the old images and these were marked as stale with no download in the last year so I thought I might as well delete them. Maybe I looked at the wrong page and mistakenly deleted and active image.
Thanks for the heads up - I'll keep the images longer.
