### ISSUE TITLE
search function does not work at habapp.readthedocs.io

### ISSUE THREAD

**Issue by alfista2600** [spacemanspiff2007/HABApp#409]
just in case you are not aware, the search function hasn't worked for a while on both safari or chrome on my Mac, or on another Mac.

https://habapp.readthedocs.io/en/latest/search.html?q=eventsChannelTriggeredEvent

might slow adoption.

**Comment by spacemanspiff2007** [comment]
Thanks for the issue. Already fixed on DEV
