### ISSUE TITLE
problem with .latest method

### ISSUE THREAD

**Issue by chris-hunter** [spacemanspiff2007/HABApp#410]
Dear Spacemanspiff, 
Thank you for the excellent habapp.  I have run into a problem with using the .latest method with an .every job.  When I use this, the rule loads ok and the .every job runs fine until the .latest time, but then habapp seems to hang and I have to restart it.  There is no error in the logs at this time (all the logs stop logging anything).
I am using HABApp version 1.1.2, openhab version 4.0.2, python version 3.10.12 on ubuntu 22.04.3.
My rules file is as follows:

```
import logging
from HABApp import Rule
from datetime import time, timedelta
log = logging.getLogger('RuleLog')

class SchedulerPractice(Rule):
    def __init__(self):
        super().__init__()

        lights_off_job = self.run.every(start_time=time(21, 15, 00), interval=timedelta(
            seconds=30), callback=self.scheduler_practice_method)
        lights_off_job.latest(time(21, 17, 00))

    def scheduler_practice_method(self):
        log.info(f'scheduler_practice_method called')

SchedulerPractice()

```

**Comment by spacemanspiff2007** [comment]
Thank you for your report. I can reproduce this issue.

**Comment by spacemanspiff2007** [comment]
I've provided a fix in the dev branch. Can you [try it out](https://habapp.readthedocs.io/en/latest/installation.html#install-a-development-version-of-habapp) and confirm everything works as expected?

**Comment by chris-hunter** [comment]
Thanks - I've tried it and it seems to be working now
