### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by spacemanspiff2007** [spacemanspiff2007/HABApp#413]
Docker build of latest release [failed](https://github.com/spacemanspiff2007/HABApp/actions/runs/6154725705/job/16700523239#step:6:1733)

@DerOetzi
Since you wrote the current docker file - would you mind looking at the issue or guide me in the right direction?
Thank you for your help!

**Comment by DerOetzi** [comment]
Yes, I can take a look at it by the end of the week.

**Comment by DerOetzi** [comment]
First quick look:

```
#14 630.3       Building wheels for collected packages: maturin
#14 630.3         Building wheel for maturin (pyproject.toml): started
#14 630.3         Building wheel for maturin (pyproject.toml): finished with status 'error'
```
On arm/v6 architecture the build for this package maturin fails. I think there are no prebuild wheels for this package for this arch. You have to find which debian dev packages are needed and install them via apt-get in build part of the top of Dockerfile

Another hint: I'm not sure the arm/v6 is really good supported by python 3.11 base container

**Comment by spacemanspiff2007** [comment]
If the fix is to remove arm/v6 then I think this is what we should do.
I think arm/v6 is the pi zero and nobody is running docker container there anyway.

**Comment by spacemanspiff2007** [comment]
Removing arm/v6 fixes ci.

Thank you for your help!
