### ISSUE TITLE
New things that do not work:

### ISSUE THREAD

**Issue by alfista2600** [spacemanspiff2007/HABApp#417]
I am admittedly behind the documentation curve, too busy to test, and not as smart as those supporting development, but:

what happened to this construct?
HABApp.openhab.interface.send_command

and how do I detect the type of a item, in lieu of this?
HABApp.openhab.interface.get_item(device, metadata=None, all_metadata=False).type

**Comment by spacemanspiff2007** [comment]
> what happened to this construct?
> HABApp.openhab.interface.send_command

The module was renamed because it was never part of the official api.

```python
OpenhabItem.get_item('my_name').send_command('bla')
```

> and how do I detect the type of a item, in lieu of this?
> HABApp.openhab.interface.get_item(device, metadata=None, all_metadata=False).type

Why would you use this instead of 
```python
item = OpenhabItem.get_item('my_name')
is_switch = isinstance(item, SwitchItem)
```

**Comment by alfista2600** [comment]
> Why would you use this instead of

Most likely because I am a lousy coder! Just do what I can to get things to work and move on. Will use your example as I rewrite code.

**Comment by spacemanspiff2007** [comment]
Are you aware of the difference between the two solutions?
My example uses the local item cache of HABApp and your original solution queried openHAB every time for the item definition.
