### ISSUE TITLE
Use of Parameters in Examples seems wrong

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#77]
The example for how to use parameters given here https://habapp.readthedocs.io/en/latest/parameters.html does not seem correct::
```
# construct parameter once, default_value can be anything
self.min_value = HABApp.Parameter( 'param_file_testrule', 'min_value', default_value=10)
```
I could not get this to work. The first argument has to be a `HABApp.Parameters` instance, and  `HABApp.Parameter` doesn't seem right either.

I finally implemented parameters like this:
```
class FileParameters(HABApp.Rule):
    def __init__(self, filename):
        super().__init__()

        self.chromecast_params = self.get_rule_parameter(
                    filename,
                    'chromecast',
                    default_value={ 'http_server': '192.168.100.119',
                                    'chromecasts' : {
                                    'Google Home Upstairs': {'ip': '192.168.100.201', 'port': 8009},
                                    'Google Mini 1': {'ip': '192.168.100.80', 'port': 8009},
                                    }
                                  }
                    )
                    
        self.prowl_api = self.get_rule_parameter(
                    filename,
                    'prowl_api',
                    default_value='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
                    )

params = FileParameters('param_file_rules')

# Define chromecasts here
ccs=[]
for name, cc in params.chromecast_params.value['chromecasts'].items():
    #log.info('loaded chromecast_params: %s: host=%s port=%s http_server:%s' % (name, cc['ip'], cc['port'], params.chromecast_params.value['http_server']))
    ccs.append(GoogleHome(host=cc['ip'], port=cc['port'], ip=params.chromecast_params.value['http_server']))
```

I have to use `.value` all the time to access the stored parameters, is that what is intended? or am I using this wrong?

Thanks,

**Comment by spacemanspiff2007** [comment]
Are you sure you are running [V0.8.0](https://github.com/spacemanspiff2007/HABApp/releases) because ``HABApp.Parameter`` has been reworked in Version.

>I have to use .value all the time to access the stored parameters, is that what is intended? or am I using this wrong?

If you want to further process the value from the file you have to use ``value``, if you just want to compare against another value you can do so without.
If I use ``Parameters`` to setup something I typically get the top-level dict with ``HABApp.Parameter(...).value`` and access everything else like a normal dict.

**Comment by NickWaterton** [comment]
Hmm, no the version number I get is `0.7.2`.

OK so I just updated to `0.8.0` I didn't notice a new version was out.

I will recheck things now...

**Comment by NickWaterton** [comment]
OK, `HABApp.Parameter` works as described now.

Thanks.
