### ISSUE TITLE
Race condition on Restored items

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#78]
This is a bit of an odd one (and i am on `0.8.0` now).

I had to reboot my OH VM. I started HABApp, but OH takes a while to get going.

I found that Items that are restored by persistence at startup sometimes give states of `None`, even after they have been restored. Not all of them do, just some.

The only way out of this was to restart HABApp, when the state of the items was then picked up.

This is a big problem when restarting, as it's hard to tell when an Item state has been restored by persistence, and HABApp does not pick up the new restored state, it just keeps reporting `None` as the state.

The item does exist as far as HABApp is concerned (I checked), just HABApp gets the wrong state when using `get_item_state()` or any of the other item methods.

Does `get_item_state()` not pull the value directly from OH? is it using a local cached version that does not get updated when items are restored by persistance? is there a way of forcing an update?

Thanks,

**Comment by spacemanspiff2007** [comment]
> Does get_item_state() not pull the value directly from OH? is it using a local cached version that does not get updated when items are restored by persistence? is there a way of forcing an update?
Correct - it's a locally cached since it is possible to use non openhab items (e.g. MQTT or even items that just exist locally for automation).

Strange - openhab should send the corresponding item events (on restore) and then HABApp should pick it up accordingly. Do you observe any errors in the HABApp log? If there are unknown events there should be an error message.

**Comment by NickWaterton** [comment]
My logs don't go back far enough to check (they fill quickly, might have to change some log parameters).

I'll keep an eye on it, see if I can grab more details, it only happened during a restart, which is a rare thing...

**Comment by spacemanspiff2007** [comment]
> I don't know if it's relevant, but the Items in question have no channel/binding, they are just variables that I use for storing/displaying numbers.

It doesn't matter since all items are treated equal.

**Comment by spacemanspiff2007** [comment]
Couldn't you just additional use mapdb for restoring state on startup?
This way all items would be restored immediately.

**Comment by NickWaterton** [comment]
I do use mapdb for restoring some items (might explain why the problem is only with some values), but mapbd only stores the last value, so you can't use it for graphing, or for historical values.

Hence I have a lot of items stored in rrd4j persistence. Does this not restore properly?

I will move to 0.9.0 as well.

**Comment by spacemanspiff2007** [comment]
I have a group which restores from mapDB and use this exclusively to restore the state on startup.
You can define multiple persistence services per item.

>Hence I have a lot of items stored in rrd4j persistence. Does this not restore properly?

Strange - it actually should

**Comment by spacemanspiff2007** [comment]
I have created the ````wait_for_openhab```` config switch a while ago which should fix this issue
