### ISSUE TITLE
Suggested Improvement for SwitchItem

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#81]
I have a suggestion for `SwitchItem`.

Right now, a `SwitchItem` only accepts boolean values, ie 'ON' or 'OFF'. This makes things difficult what you are setting switches to be controlled by `DimmerItems` which use both OnOff and percent types. I can control a `DimmerItem` with a `SwitchItem`, as the `DimmerItem` accepts 'ON' and 'OFF' inputs, but not vice versa.

My workaround is this:
```
if isinstance(master_item, SwitchItem):
    if event.value > 0:
        event.value = 'ON'
    else:
        event.value = 'OFF'
```
Which is horrible.

I would suggest adding `PercentCommand` to `SwitchItem` such that any value > 0 is ON and 0 is OFF.
This way, a `SwichItem can be controller by a `DimmerItem`.

Here is my hack for `SwitchItem`:
```
if isinstance(new_value, OnOffValue):
    new_value = new_value.value
elif isinstance(new_value, PercentValue):
    new_value = OnOffValue.ON if new_value.value > 0 else OnOffValue.OFF
```
Should really add `percent` as a method to `OnOffCommand` as well, but I haven't figured out how all this goes together yet.

so then you can do this:
```
flouro_item = self.get_item('basementFluorescents')
flouro_item.set_value(event.value)
self.log.info('setting basementFluorescents to %s' % flouro_item)
self.oh.post_update('basementFluorescents', flouro_item)
```
and it doesn't matter if `event.value` is 'ON', 'OFF', or a percent number.

What do you think? is it worth doing? I can make my own routine to figure this out, but this would be more elegant.

**Comment by spacemanspiff2007** [comment]
I do not understand what are you trying to do. Could you provide more of the code in the rule please?

Unrelated:
You can shorten your snippet to:

````python
# this part is not necessary, once the item updates in openhab
# the value will change automatically in HABApp, too
# flouro_item = self.get_item('basementFluorescents')
# flouro_item.set_value(event.value)
self.log.info('setting basementFluorescents to %s' % event.value)
self.oh.post_update('basementFluorescents', event.value)
````

Always use class factories - this will provide auto complete in the IDE and type cheching during runtime

````python
flouro_item = self.get_item('basementFluorescents')        # BAD!
HABApp.openhab.DimmerItem.get_item('basementFluorescents') # good
````

**Comment by NickWaterton** [comment]
I think I'm getting the hang of it now (famous last words!). I'll post the whole rule when I have it working properly.

What I'm trying to do, is to control two lights, both of which are dimmers, with one item, which is a switch (this is an actual insteon set up). Insteon is a bit odd - there is no physical connection between the switch and the lights, when you use the switch, the lights go on and off together, because they are are "linked" at the insteon level.

The problem comes with OH. When you send the command 'ON' to the switch, it turns the switch on, but not the linked devices - hence I need a rule that does the linking in OH.

For the switch (in OH) to turn the dimmers on is easy. I take the 'ON' notification from the switch, and and it to both dimmers. DimmerItems accept 'ON' and 'OFF' as valid commands

For the dimmers to turn the switch on is hard, because the dimmers send PercentValue (or string, or float) events, and I can't send that to a switch, because it only accepts OnOffValues. So I say in the rule that anything more than 0 is 'ON' and send it to the switch. The type of event you receive changes with the type of trigger event, so this complicates matters.

This is a common scenario is three ways switches, so I want to make the rule generic, so it can handle any combination of dimmers/switches. This makes things more complicated, as I have to determine what kind of item the source is, and what kind of item the destination is, because they don't accept the same type of values. If both DimmerItems and SwitchItems accepted the same inputs (OnOffValue, PercentValue), then there would be no need for this.

The final issue is that you can get stuck in a loop if you are not careful.
ie, The switch sends 'ON' (from OH), I send '100' to the Dimmer items, the rule receives '100' from the dimmers, which triggers the rule to send 'ON' to the switch - and before you know it you're in a loop. I need to pick the event triggers carefully to prevent this, but changing the trigger type changes the type of event you receive. `ItemCommandEvent` gives you different event types from `ValueChangedEvent` for instance.

My proposal was to make a SwitchItem accept PercentValues like a DimmerItem, with anything more than 0 as 'ON'. This makes half of the complications go away.

When I have a working rule, I'll post it and you can see what I mean.

**Comment by spacemanspiff2007** [comment]
Could you not just call the ``on()`` method of the item? This will send the openhab command ON to the openhab item which should work with both item types.

**Comment by NickWaterton** [comment]
On and OFF are not the problem, the problem is that the dimmers don't send ON and OFF, they send PercentValues, which I can't send to a SwitchItem.

Here is my working rule. It's nasty, but it works. `get_as_numeric` has a lot of stuff in it, but it's mostly for testing:
```
class SyncLights(HABApp.Rule):
    '''
    Generic rule to sync Insteon master and slave items, in a 3 way (or more) configuration
    either SwitchItems or DimmerItems are handled as Master or Slaves.
    '''
    def __init__(self, master_item, *args):
        super().__init__()
        self.log = logging.getLogger('MyRule.'+self.__class__.__name__)
        
        self.master_item = master_item  #'basementFluorescents'
        self.slaves = list(args)

        self.ignore = 0
        
        self.listen_event( self.master_item, self.master_item_command, ItemCommandEvent)
        for slave in self.slaves:
            self.listen_event( slave, self.slave_item_command, ItemCommandEvent)
 
    def master_item_command(self, event):
        self.log.info('Master Item %s received command %s' % (event.name, event.value))
        self.ignore = 0
        self.set_slave(self.get_as_numeric(event.value))    # cannot compare OnOffvalue with PercentValue so convert to numeric (ON=100)
        
    def set_slave(self, value):
        try:
            for slave in self.slaves:
                if self.get_as_numeric(self.get_item_state(slave)) != value:    # cannot compare state with OnOffValue or Percentvalue so have to convert
                    item = self.get_item(slave)
                    value = self.convert_value(item, value) # cannot send PercentValue or number to SwitchItem, so have to convert
                    self.log.info('setting %s to %s' % (slave,value))
                    self.ignore += 1                        # ignore incoming ItemCommandEvent caused by send_command
                    self.oh.send_command(slave, value)

        except Exception as e:
            self.log.error(e)
            
    def slave_item_command(self, event):
        self.log.info('Slave %s received command %s' % (event.name, event.value))
        if self.ignore:                                     # If ItemCommandEvent was triggered by master Item, ignore it
            self.ignore -=1
            self.log.info('Slave: ignoring command %s' % self.ignore)
            return
        self.set_master(event.name, self.get_as_numeric(event.value))   # cannot compare OnOffvalue with PercentValue so convert to numeric (ON=100)
        
    def set_master(self, name, value):
        try:
            max_val = value
            slaves = self.slaves.copy()
            slaves.remove(name)                                         # remove item that triggered event from comparison list, triggering value is value, not state
            for slave in slaves:
                max_val = max(self.get_as_numeric(self.get_item_state(slave)), max_val) # get the max value of all slave items (ON = 100)
            self.log.debug('max_val : %s' % max_val)
            master_item = self.get_item(self.master_item)
            value = self.convert_value(master_item, max_val)            # cannot send PercentValue or number to SwitchItem, so have to convert
            if master_item.value != value:
                self.log.info('setting %s to %s' % (self.master_item, value))
                self.oh.post_update(self.master_item, value)            # only need to post_update master value, avoids loop
                    
        except Exception as e:
            self.log.error(e)
            
    def get_as_numeric(self, item):
        '''
        Horrible thing to convert any value, either state, OnOffvalue, PercentValueor or anything else
        (int, float) to a numeric value
        ON=100, OFF=0, None = 0
        '''
        
        if item is None:
            self.log.debug('Item is %s returning 0' % item)
            return 0
        elif isinstance(item, OnOffValue):
            self.log.debug('OnOffValue: %s' % item)
            if item.value == OnOffValue.ON:
                return 100
            else:
                return 0
        elif isinstance(item, PercentValue):
            self.log.debug('PercentValue: %s' % item)
            return int(item.value)
        elif isinstance(item, SwitchItem):
            self.log.debug('SwitchItem: %s' % item)
            if item.is_on():
                return 100
            else:
                return 0
        elif isinstance(item, int):
            self.log.debug('int: %s' % item)
            return item
        elif isinstance(item, str):
            self.log.debug('str: %s' % item)
            if item == 'ON':
                return 100
            elif item == 'OFF':
                return 0
            return int(item)
        elif isinstance(item, float):
            self.log.debug('float: %s' % item)
            return int(item)
        self.log.debug('unknown: %s' % item)
        return int(item.value)
            
    def convert_value(self, item, value):
        '''
        Takes a numeric value, and returns a value compatible with item type
        ie if item is a SwitchItem, return 'ON' or 'OFF' as Switchitem cannot accept numerical values.
        otherwise just return the numerical value unchanged.
        '''
        if isinstance(item, SwitchItem):
            if value > 0:
                value = 'ON'
            else:
                value = 'OFF'
        return value
 
SyncLights('basementFluorescents', 'basementPanelFront', 'basementPanelBack')
```

Is there a better way than this to synchronize Switch and Dimmer items?

**Comment by spacemanspiff2007** [comment]
I'm just writing this down without trying, so please don't expect it to work 100% percent.

````python
import typing
import HABApp
from HABApp.openhab.events import ItemCommandEvent, ItemStateEvent
from HABApp.core.items import Item

class SyncLights(HABApp.Rule):
    
    def __init__(self, master_item: str, slaves: typing.List[str] = []):
        super().__init__()
        self.log = logging.getLogger('MyRule.' + self.__class__.__name__)
        
        self.master_item: Item = self.get_item(master_item)
        self.slave_items: typing.List[Item] = [self.get_item(k) for k in slaves]
        
        self.listen_event(self.master_item, self.master_item_command, ItemStateEvent)
        for slave in self.slave_items:
            self.listen_event(slave, self.slave_item_command, ItemCommandEvent)
    
    def master_item_command(self, event: ItemCommandEvent):
        for s in self.slave_items:
            self.update_state(event, s)
    
    def slave_item_command(self, event: ItemCommandEvent):
        # just send the command to master, the slaves will update 
        # as soon as we process the command there
        self.update_state(event, self.master_item, send_command=True)
    
    def update_state(self, event: ItemCommandEvent, target_item: Item, send_command=False):
        
        value = event.value
        
        # Switch: we have to do conversion
        if isinstance(target_item, HABApp.openhab.items.SwitchItem):
            if isinstance(value, (int, float)):
                value = 'ON' if value else 'OFF'
        else:
            # Dimmer, we do nothing
            assert isinstance(target_item, HABApp.openhab.items.DimmerItem), target_item
        
        if send_command:
            self.openhab.send_command(target_item.name, value)
        else:
            self.openhab.post_update(target_item.name, value)

````

**Comment by NickWaterton** [comment]
Thanks for the suggestion.

I am obviously doing a bad job of explaining myself.

You rule doesn't work, as you have the send_command the wrong way round, and if you change it to be the right way round, you get a send_command loop as I mentioned earlier (you have to `send_command` to the slave_items or the actual lights will not turn on/off).

There are some useful ideas in your code though. I will take my prototype rule and try to make it simpler using your example as a guideline

**Comment by NickWaterton** [comment]
Here is my simplified rule, based on your example:
```
class SyncLights(HABApp.Rule):
    '''
    Generic rule to sync Insteon master and slave items, in a 3 way (or more) configuration
    either SwitchItems or DimmerItems are handled as Master or Slaves.
    '''
    def __init__(self, master_item: str, *slaves):
        super().__init__()
        self.log = logging.getLogger('MyRule.' + self.__class__.__name__)
        
        self.master_item: Item = self.get_item(master_item)
        self.slave_items: typing.List[Item] = [self.get_item(k) for k in list(slaves)]
        
        self.ignore_command = 0
        
        self.listen_event(self.master_item, self.master_item_command, ItemCommandEvent)
        for slave in self.slave_items:
            self.listen_event(slave, self.slave_item_command, ItemStateChangedEvent)
    
    def master_item_command(self, event: ItemCommandEvent):
        self.log.info('Master %s received command %s' % (event.name, event.value)) 
        self.ignore_command = 0
        for s in self.slave_items:
            self.update_state(event, s, send_command=True)
    
    def slave_item_command(self, event: ItemStateChangedEvent):
        self.log.info('Slave %s changed to %s' % (event.name, event.value))
        # just send the command to master, the slaves will update 
        # as soon as we process the command there
        if not self.ignore: # If ItemStateChangedEvent was triggered by master Item update, ignore it
            event.value = self.get_slave_max_value(event)
            self.update_state(event, self.master_item)
    
    @property
    def ignore(self):
        if self.ignore_command:
            self.ignore_command -=1
            self.log.debug('Slave: ignoring command %s' % self.ignore_command)
            return True
        return False
        
    def get_slave_max_value(self, event):
        slaves_max = [self.get_int(slave.value) for slave in self.slave_items if slave.name != event.name]
        slaves_max.append(self.get_int(event.value))
        return max(slaves_max)
        
    def get_int(self, value):
        if value is None:
            self.log.debug('value is %s returning 0' % value)
            return 0
        elif str(value) == 'ON':
            return 100
        elif str(value) == 'OFF':
            return 0
        try:
            return int(value)
        except TypeError:      # probably PercentValue
            return int(value.value)
    
    def update_state(self, event: ItemCommandEvent, target_item: Item, send_command=False):
        
        value = event.value
        
        # Switch: we have to do conversion
        if isinstance(target_item, HABApp.openhab.items.SwitchItem):
            if isinstance(value, (int, float)):
                value = 'ON' if value else 'OFF'
        else:
            # Dimmer, we have to convert to int (cant send_command a PercentValue!
            assert isinstance(target_item, HABApp.openhab.items.DimmerItem), target_item
            value = self.get_int(value)
            
        if target_item.value != value:
            if send_command:
                self.log.info('%s send command %s' % (target_item.name, value))
                self.ignore_command +=1
                self.openhab.send_command(target_item.name, value)
            else:
                self.log.info('%s post update %s' % (target_item.name, value))
                self.openhab.post_update(target_item.name, value)
 
SyncLights('basementFluorescents', 'basementPanelFront', 'basementPanelBack')
SyncLights('porchLight', 'porchLightKuna', 'drivewayLightKuna')
SyncLights('gardenLight', 'gardenLightKuna')
SyncLights('kitchenUCLED', 'kitchenUCSlave')
SyncLights('hallwayLight', 'hallwaySlave')
SyncLights('landingMain', 'landingSlave')
SyncLights('livingLight', 'livingLamp1', 'livingLamp2')
```
Thank you for your help!

Things that I have come across in the course of this (for consideration):
1)  `ItemStateEvent` causes one or two event triggers, one for the command (if there is one) and one for the state change, and there is no way to differentiate between the two. This makes the event difficult to use.
2) `PercentValue` is difficult to use (returned by event), as you can't compare it with a value, you cant convert it to an int (has a '%' symbol in the `str()` representation) and you can't use `send_command` or `post_update` with it (because of the '%' symbol. This requires special handling to use value.value (float) for all `Percentvalue` events.
3) have to use special trapping to prevent an `ItemCommandEvent` loop.

Of these, the `PercentValue` issue is probably the biggest, and may be unintended. I think the string representation of it should omit the '%' symbol, then you could just send a `PercentValue` to an OH `DimmerItem` (using `send_command`, or `post_update`)with no conversion needed.

**Comment by spacemanspiff2007** [comment]
> You rule doesn't work, as you have the send_command the wrong way round, and if you change it to be the right way round, you get a send_command loop as I mentioned earlier (you have to send_command to the slave_items or the actual lights will not turn on/off).

I don't see how I am creating a loop:
If you click a slave in the sitemap it'll send a command to the master and update the slaves with the correct state. If you click the master in the sitemap, the slaves will be updated with the master slave. There is no repetition of commands and I am using ````post_update```` instead of ````send_command````.

1. ````ItemStateEvent```` always fires if the item state changes or updates.  ````ItemCommandEvent```` fires only if an item received a command

2. just use ````PercentValue() .value````, it should pop in your IDE when hitting the ````.````. I hope you use an IDE?

**Comment by spacemanspiff2007** [comment]
I just found a bug where the PercentValue did not get reduced to the corresponding value.
So this might help you quite a bit. I'll fix it in 0.9.2.

**Comment by NickWaterton** [comment]
Thanks, the PercentValue fix helps a lot.

**Comment by spacemanspiff2007** [comment]
No, this is not possible. There must be something wrong on your side - could you double check please?
A command triggers an ``ItemCommandEvent`` typically followed by ``ItemStateEvent`` and then by ``ItemStateChangedEvent``

**Comment by spacemanspiff2007** [comment]
@NickWaterton : Any update?

**Comment by NickWaterton** [comment]
I have it working, but still run into odd circumstances.

here is my initialization method:
```
    def initial_sync(self):
        #initial sync to master:
        if self.master_item.value is not None:
            #self.log.info('initial sync of: %s to %s' % (self.master_item.name, self.master_item.value))
            event = ValueUpdateEvent(name=self.master_item.name, value=self.master_item.value)
            for s in self.slave_items:
                self.update_state(event, s, send_command=True)
        self.ignore_command = 0
```
This initially syncs the various switches/dimmers when habapp is started.

I started running into a problem where a dimmer item (master item) would return a value '0' but as a string, not an int or a float. Happens on startup.

I added a trap for it.

I guess it's just confusing all these ints, floats and strings to represent integers. To me they should just all be ints.

It would be easy if the str representation was "OFF" "ON", "%" etc, and the value was always an int with 0 == OFF and 100 == ON.. It makes handling difficult when you don't know if an item.value is an int, float or string.

Of course then you have to worry about event.value in an event. is that an int, float or string? maybe what we need is a new property `.int_val` which always returns the value as an integer, 1 == OPEN/ON, 0 == OFF/CLOSED etc.

Any thoughts on how to handle this better?

**Comment by spacemanspiff2007** [comment]
Couldn't you sync the dimmer and the switch like this:
```python
if my_switch.is_on():
    my_dimmer.on()
if my_switch.is_off():
    my_dimmer.off()
```

**Comment by NickWaterton** [comment]
No, because the value of the dimmer can change to a % value, and then you have to update the switch (which can be a dimmer or a switch) to `ON` from a % like 70%.

If you imagine the simplest configuration, you have one light, but two physical switches controlling it. The switches can be either dimmers or switches, or one of each. Only one physical switch/dimmer controls the light, the other switch/dimmer has no physical connection to the light. This is a common set up called a `3 way switch`.

The dimmers have lights on them that show the brightness (or on/off) and are represented by a single switch or slider in the OH interface, which also shows the current state (of the switch they represent - the one connected to the light).

You can set the light to 80% by using either physical dimmer, or the slider in OH. If you use the slider in OH, you have to also update the other physical dimmer to 80%. If you use the physical dimmer (or switch) you also have to update the other physical dimmer, and possibly the OH slider (if the dimmer/switch is not the one connected to the OH slider).

You can't just copy the value to all the other devices, as switches can't accept % values, so you have to intercept the value and convert it to `ON/OFF`, which means you have to know what the target type is.

This is the simplest configuration. Now imagine you have three switches/dimmers, or the light is not connected to a physical switch (I have several LED light bulbs/panels that you can set to a % brightness with no physical switch), or you have two lights and two dimmers... You can see how this gets complicated in a hurry.

I do have my rule working successfully though:
```
class SyncLights(HABApp.Rule):
    '''
    Generic rule to sync Insteon master and slave items, in a 3 way (or more) configuration
    either SwitchItems or DimmerItems are handled as Master or Slaves.
    '''
    def __init__(self, master_item: str, *slaves: tuple()):
        super().__init__()
        self.log = logging.getLogger('MyRule.' + self.__class__.__name__)
        
        self.master_item: Item = Item.get_item(master_item)
        self.slave_items: typing.List[Item] = [Item.get_item(k) for k in list(slaves)]
        
        self.ignore_command = 0
        self.t = 1 # set to ramp rate for lights in question
        self.timer = createTimer(self.t, self.enable, run=False)
        
        self.listen_event(self.master_item, self.master_item_command, ItemStateChangedEvent) #ItemCommandEvent
        for slave in self.slave_items:
            self.listen_event(slave, self.slave_item_command, ItemStateChangedEvent)
            
        self.initial_sync()
            
    def initial_sync(self):
        #initial sync to master:
        if self.master_item.value is not None:
            #self.log.info('initial sync of: %s to %s' % (self.master_item.name, self.master_item.value))
            event = ItemStateEvent(name=self.master_item.name, value=self.master_item.value)
            for s in self.slave_items:
                self.update_state(event, s, send_command=True)
        self.ignore_command = 0
    
    def master_item_command(self, event: ItemStateChangedEvent):
        self.log.info('Master %s changed to %s' % (event.name, event.value)) 
        if not self.ignore: # If ItemStateChangedEvent was triggered by master Item update, ignore it
            for s in self.slave_items:
                self.update_state(event, s, send_command=True)
    
    def slave_item_command(self, event: ItemStateChangedEvent):
        self.log.info('Slave %s changed to %s' % (event.name, event.value))
        # just send the command to master, the slaves will update 
        # as soon as we process the command there
        if not self.ignore: # If ItemStateChangedEvent was triggered by master Item update, ignore it
            event.value = self.get_slave_max_value(event)
            self.update_state(event, self.master_item, send_command=True)
    
    @property
    def ignore(self):
        if self.ignore_command:
            self.ignore_command -=1
            self.log.debug('Slave: ignoring command %s' % self.ignore_command)
            return True
        return False
        
    def start(self):
        self.ignore_command = 10
        self.log.debug('updates disabled for: %ss' % self.t)
        self.timer.start()
        
    def enable(self):
        self.ignore_command = 0
        self.log.debug('updates enabled')
        
    def get_slave_max_value(self, event):
        slaves_max = [self.get_int(slave.value) for slave in self.slave_items if slave.name != event.name]
        slaves_max.append(self.get_int(event.value))
        return max(slaves_max)
        
    def get_int(self, value):
        if value is None:
            self.log.debug('value is %s returning 0' % value)
            return 0
        elif str(value) == 'ON':
            return 100
        elif str(value) == 'OFF':
            return 0
        try:
            return int(value)
        except TypeError:      # just in case
            return int(value.value)
        except ValueError:
            return int(float(value))    #maybe a float
    
    def update_state(self, event: ItemCommandEvent, target_item: Item, send_command=False):

        value = event.value

        # Switch: we have to do conversion
        if isinstance(target_item, HABApp.openhab.items.SwitchItem):
            if isinstance(value, (int, float)) or value.isdigit():
                value = 'ON' if int(value) > 0 else 'OFF'
        else:
            # Dimmer, leave value as is
            assert isinstance(target_item, HABApp.openhab.items.DimmerItem), target_item
        
        if self.get_int(target_item.value) != self.get_int(value):
            self.start()
            self.ignore_command +=1
            if send_command:
                self.log.info('%s send command %s' % (target_item.name, value))
                self.openhab.send_command(target_item.name, value)
            else:
                self.log.info('%s post update %s' % (target_item.name, value))
                self.openhab.post_update(target_item.name, value)
        #else:
        #    self.log.info('not sending value: %s to target: %s' % (value, target_item.name))

 
SyncLights('basementFluorescents', 'basementPanelFront', 'basementPanelBack')
SyncLights('porchLight', 'porchLightKuna', 'drivewayLightKuna')
SyncLights('gardenLight', 'gardenLightKuna')
SyncLights('kitchenUCLED', 'kitchenUCSlave')
```

**Comment by spacemanspiff2007** [comment]
I still think this is way to complicated - but maybe I still don't understand the problem correctly.
Imho this rule should forward the state of the master to all slaves and if a slave receives a command forward it to the master (untested).

```python

class SyncLights(HABApp.Rule):
    def __init__(self, *args):
        super().__init__()

        self.master = args[0]
        assert isinstance(self.master, HABApp.openhab.items.OpenhabItem)
        self.listen_event(self.master, self.master_command, HABApp.openhab.events.ItemCommandEvent)

        self.synced_items = tuple(HABApp.openhab.items.OpenhabItem.get_item(k) for k in args[1:])
        for name in self.synced_items:
            self.listen_event(name, self.forward_command, HABApp.openhab.events.ItemCommandEvent)

    def initial_sync(self):
        # Send a command with the current value
        self.openhab.send_command(self.master, self.master.value)

    def master_command(self, event: HABApp.openhab.events.ItemCommandEvent):
        for item in self.synced_items:
            value = event.value
            if isinstance(value, str):
                value = 100 if value == 'ON' else 0

            if isinstance(item, HABApp.openhab.items.SwitchItem):
                self.openhab.post_update(item, 'ON' if value else 'OFF')
            else:
                # assume it's a dimmer
                self.openhab.post_update(item, value)

    def forward_command(self, event: HABApp.openhab.events.ItemCommandEvent):
        self.openhab.send_command(event.name, event.value)

```

**Comment by NickWaterton** [comment]
You'd have to try this in reality to see the issues. One of the main problems is that actuating a real world switch or dimmer does not generate an `ItemCommandEvent`, it generates an `ItemStateChangedEvent`, which is why I listen for these not command events.

`ItemCommandEvent` events are only generated from the OH interface (ie the UI), but a change in the UI will also generate an `ItemStateChangedEvent`. If you are not careful, listening for these events, you quickly get into a loop, which is where the `ignore` parameter comes in, ie if I receive a state change from a slave, and pass it to the master, I will get a state change event from the master, that I then need to ignore.

Complicating the matter is that the dimmer switches/lights have a "ramp rate" - the rate that they change from 0 to 100%. This is configurable, and is usually 0.5s - but in some cases is more. This means that you have to ignore state changes for a period of time (this is `self.t`), it's not instantaneous, and they can send state updates while they are changing (ie they can send an update at 50% or so).

I could probably re-write the rule though, to simplify it some more, as I changed from an ignore count to ignore time and haven't cleaned up afterward.

**Comment by spacemanspiff2007** [comment]
> You'd have to try this in reality to see the issues. One of the main problems is that actuating a real world switch or dimmer does not generate an ItemCommandEvent, it generates an ItemStateChangedEvent, which is why I listen for these not command events.

This is correct and this is why the rule above forwards the commands from all proxy items to the master item. What you don't catch with the above rule is when you switch something on with a physical switch connected to your master device, it works just when you control it from openhab.

I think the main takeaway is that you can test if an item is a switch or a dimmer and then react accordingly. This snipped should be sufficient and the solution for you.
````
            if isinstance(value, str):
                value = 100 if value == 'ON' else 0

            if isinstance(item, HABApp.openhab.items.SwitchItem):
                self.openhab.post_update(item, 'ON' if value else 'OFF')
            else:
                # assume it's a dimmer
                self.openhab.post_update(item, value)
````

Once I add custom ``post_update`` handlers (like the one for the ``ImageItem``) to the openhab items I'll react to numeric values accordingly.

I'm closing this issue for now, but please feel free to open it again.
