### ISSUE TITLE
Ping not working

### ISSUE THREAD

**Issue by andreasbrinch** [spacemanspiff2007/HABApp#82]
I have enabled ping in the config file and setup the item in openhab, but the value never gets updated. I found the function async_ping in the code but I couldn't find it being called from anywhere. Is that the issue?

I have a simple rule up and running and it gets triggered, so the system works. I am running habapp in a docker container.

**Comment by andreasbrinch** [comment]
I think you are missing a () in the call. Changing ....ensure_future(self.async_ping) to ....ensure_future(self.async_ping()) made it work for me.

**Comment by spacemanspiff2007** [comment]
Good catch - thank you!
