### ISSUE TITLE
How to get members of a Group?

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#85]
I have several rules that look like this:
```
    // all lights in group bedtime to OFF, with 100 ms Delay
    bedtime?.members.forEach[ item,i|createTimer(now.plusMillis(i*100)) [ sendCommand(item, OFF) ] ]
```
So I need to iterate over the members of the group. It I try to use the group name `bedtime` using `get_item`, I just get an item with no value and no members.

I can't figure out how groups are handled in the code. It looks like `members` is broken out, but the final group ends up as a regular Item, not a Group item.

Can you give some pointers on how to access the members of a group? or how to tell what group an item is a member of?

Or are groups not completely implemented yet?

Thanks.

**Comment by spacemanspiff2007** [comment]
You can use ```get_item``` from the openhab interface.
However this is a sync method it takes a little bit of time (depending on size etc.).
I'd rather use naming conventions and access items by name

**Comment by NickWaterton** [comment]
Ah! got it. did not realize there was a difference between the two.

That solves the problem.

Thanks,

**Comment by spacemanspiff2007** [comment]
Yes - the documentation is a little bit unsatisfying there ...
