### ISSUE TITLE
oh.post_update does not update item.value immediately

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#92]
I just ran into a minor issue with `post_update` (probably `send-command` as well).

when I `post_update` a new value to an item, then immediately use the `item.value` the value is the old value, not the new value just posted.

I realize this is because the new value is sent to OH, and at some future time the value will be updated with the new value, but this is a bit of a `"gotcha" if you don't realize this.

for example, I post a timestamp update to a `DateTime` item, then immediately display the new value. I do this as OH is a bit pickey about the DateTime formats it accepts, and sometimes it doesn't "take". I noticed that the new value displayed was wrong (avtually the old timestamp) - This was when i realized the problem.

here is the problem code:
```
def update_timestamp(self, date_time_item):
        self.oh.post_update(date_time_item, self.dt)
        self.log.info('updated %s timestamp to : %s' % (date_time_item.name, date_time_item.value))
```
where `self.dt` is `datetime.now()`

The workaround is to do a, `item.set_value()` after the `post_update` but this isn't a great solution, as you don't then know what the actual value in OH is.

This is my slightly better workaround:
```
    def timestamp_update(self, event):
        self.log.info('updated %s timestamp to : %s' % (event.name, event.value))
        self.event.cancel()
        
    def update_timestamp(self, date_time_item):
        self.oh.post_update(date_time_item, self.dt)
        self.event = self.listen_event(date_time_item, self.timestamp_update, ItemStateEvent)
```

But the "gotcha" still exists - which is OK, as long as you are aware of it.

**Comment by spacemanspiff2007** [comment]
I'm aware this is can be a little bit tricky. I typically differentiate between the openhab side for control/visualization and HABApp. 
Maybe there should be a part in the docs where this is elaborated more clearly?

> I post a timestamp update to a DateTime item, then immediately display the new value. I do this as OH is a bit pickey about the DateTime formats it accepts, and sometimes it doesn't "take"

This is strange. I have created test cases especially for datetime, so if you post a datetime obj it should always work. Can you provide an example where OH doesn't accept the datetime so I can fix this?

**Comment by NickWaterton** [comment]
You know, thinking about it it may not be a thing. I have had instances where datetimes come in via MQTT (or other external source) and OH doesn't like it, because of the way the timezone is formatted, or the milliseconds value is too long (OH didn't like six digit precision). 

So I started checking the DateTime after updating. Now in my old version I was seeing the old value, not the new, so sometimes it read as `None` (after an OH restart for instance) - but this was my mistake.

I think if I update a DateTime from within Habapp, there won't be a problem, it's only if I'm receiving the timestamp from an external source that it's an issue.

Seeing as you helpfully provide a `.last_update` property for each item, it might make more sense to use that and remain internally consistent.

Of course then you run into the old issue of do I log when the update was sent vs when it was received problem.

I probably need to go back and rethink some of my existing rules

**Comment by spacemanspiff2007** [comment]
I'm closing this - if you have further ideas or problems please reopen
