### ISSUE TITLE
Add native support for Sunrise/Sunset

### ISSUE THREAD

**Issue by spacemanspiff2007** [spacemanspiff2007/HABApp#93]
Calculation can be done through the Astral package

**Comment by spacemanspiff2007** [comment]
@NickWaterton I've done some refactoring of the scheduler. Would you be willing to test the current dev branch? There is a new function to run on sunrise, sunset, etc.

**Comment by NickWaterton** [comment]
Ok, i just pulled the dev branch, it says it's V0.10.1 which what I already have (but I'm on the dev branch now).

Everything started up OK. No errors.

What would you like me to test?

**Comment by spacemanspiff2007** [comment]
I forgot to update the version number on the dev branch - sorry.
Could you take a look at the scheduler, if the triggers get executed as expected.
Also you can play around with [the sun scheduler](https://github.com/spacemanspiff2007/HABApp/blob/0eaa6eb120eeacbd7f643eba8746bf6a4d341c47/HABApp/rule/rule.py#L210).
The scheduled objects now have a "earliest", "latest", "offset" and "jitter" method which will modify the next call time the next scheduled call or after the "update_run_time" method.

**Comment by NickWaterton** [comment]
OK, everything is working right now.
I've added as sunset and sunrise event, I'll see what happens. I was using the astro binding for this, but this would be easier.

Just FYI, I have just completed conversion of 370 OH rules to HABApp! Only a few left (difficult ones though).

**Comment by spacemanspiff2007** [comment]
> Just FYI, I have just completed conversion of 370 OH rules to HABApp! Only a few left (difficult ones though).

Oh wow - you sure have lots of them!

**Comment by NickWaterton** [comment]
Most of them are one-liners, as OH forces you to have a rule for everything...

So I have been testing sunrise and sunset events. No Sunset event yet (even at sunset), but I did get a sunrise event:
```
HABApprules.log.1:2019-12-12 00:49:44,008[           MyRule.TestRule] INFO|        sunrise_func: SUNRISE EVENT!
```
Notice it's logged at `00:49:44` ie 10 to 1 in the morning. looks like a TimeZone issue (I'm in Eastern).
This is probably why I haven't had a sunset event yet, I expect it'll show up at noon ish.

**Comment by spacemanspiff2007** [comment]
Have you set the correct location in the habapp.yml?
I forgot to tell you about it :confused:

**Comment by NickWaterton** [comment]
Probably not, I was thinking it would use the environment variables. I'll go check it now.

**Comment by NickWaterton** [comment]
Sunset event just occurred right on schedule...

**Comment by spacemanspiff2007** [comment]
Sorry, sometimes I don't remember the right filenames 😦 
Perfect - noticed any other inconsistencies with the scheduler?
