### ISSUE TITLE
QuantityType Items cause problems when trying to use them

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#94]
Since OH 2.4 a new type `QuantityType` was introduced.
This makes calculations very difficult. items now are defined like this:
```
Number:Temperature  AeonMS61F "Temperature [%.1f °C]" <temperature> (gB, Sensors, Max_Temperature) {channel="zwave:device:controller:node29:sensor_temperature"}
```
If you want the units to be converted correctly (eg Celsius not Fahrenheit) - this is the only way to get the units reported correctly.

In HABapp these items values are returned as strings like this:
```
'29.5555555555555555555555555555556 °C'
```
Which makes performing comparisons with them difficult.
The workaround I have is this:
```
temp = get_int(self.item['AeonMS61F'].value.replace('°C', ''))
```
where `get_int` is a routine that attempts to make an number out of whatever you give it.
It would be very helpful if the item `.value` returned the integer or float value of a `Number` item (even if its also a `QuantityType`), perhaps the string could be returned as the `__repr__` value or a new `.formatted` property.

It might be simpler to split the string at the first non-numeric character (that isn't`.`), but I just hacked the fix in quickly. There are obvious possible issues with `-` signs, `,` and so on, so it might need some thought.

OH does like to make things difficult, but I think it would be nice if we could work round their complications this way.

**Comment by spacemanspiff2007** [comment]
I already have added an [Issue](https://github.com/openhab/openhab-core/issues/1093) because imho the returned value from the rest api should be in the base unit without a value.

This definately needs to be fixed properly!

**Comment by spacemanspiff2007** [comment]
I added a quick fix for it in the dev branch

**Comment by NickWaterton** [comment]
Thanks for the quick fix.
I'm not sure how to use it though. Now, instead of getting an int or a float, `.value` is a `QuantityValue`.

if you try to use `.value` as a number you get this sort of thing:
```
2019-12-12 10:02:25,547[             HABApp.Worker]ERROR|  __format_traceback:     temp = round(self.item['AeonMS61F'].value, 2)
2019-12-12 10:02:25,548[             HABApp.Worker]ERROR|  __format_traceback: TypeError: type QuantityValue doesn't define __round__ method
```
or
```
2019-12-12 10:13:27,804[             HABApp.Worker]ERROR|  __format_traceback:     temp = round(float(self.item['AeonMS61F'].value), 2)
2019-12-12 10:13:27,805[             HABApp.Worker]ERROR|  __format_traceback: TypeError: float() argument must be a string or a number, not 'QuantityValue'
```
you get this is you try to format it in a string ie `'value %.2f' % item.value`:
```
2019-12-12 10:16:37,023[             HABApp.Worker]ERROR|  __format_traceback: TypeError: must be real number, not QuantityValue
```
I think `.value` should be an int or a float not a `QuantityValue`, it's hard to tell what `Number` items will be a plain number or a `QuantityValue` so I don't want to have to treat them differently. To me, temperature, humidity etc. should all just be numbers.

**Comment by NickWaterton** [comment]
here is `get_float()`

```
re_float = re.compile('\d+(?:\.\d+)?')    
def get_float(value, places=2):
    if value is None:
        log.debug('value is %s returning 0' % value)
        return 0.0
    elif str(value) == 'ON':
        return 100.0
    elif str(value) == 'OFF':
        return 0.0
    try:
        return round(float(value), places)
    except TypeError:      # just in case
        return round(float(value.value), places)
    except ValueError:
        m = re_float.search(value)
        return round(float(m.group()), places) if m else 0.0   #maybe a float embedded in a string
```
hopefully this should sort out my numbers problem.

**Comment by spacemanspiff2007** [comment]
I have uploaded a fix, QuantityTypes should now be fully supported.
Can you please verify that your issues are gone?

**Comment by NickWaterton** [comment]
See my comments in issue #91 Unfortunately `QuantityTypes` don't work - can't start up HABApp at all. Had to do a hack to get it to start, so I can't test them out.

Basically you can't start HABApp if any of your items are `QuantityTypes` as `opernhab.items.map_items()` maps them to a `NumberItem` which then causes a `ValueError` when trying to convert it to a float - this is an untrapped error and it all goes off the rails from there.

I wrote up the work around in issue #91 as at that point I wan't sure what part of the new functionality was causing the problem.
