### ISSUE TITLE
Getting messages 'X' took too long

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#96]
I have just recently (on the dev branch) started getting these messages:
```
2019-12-16 14:30:02,868[             HABApp.Worker]WARNI|               __run: Execution of Alexa.realitem_update_received took too long: 1.26s
2019-12-16 14:30:13,507[             HABApp.Worker]WARNI|               __run: Execution of LuxtoText.item_state_update took too long: 1.09s
2019-12-16 14:40:49,397[             HABApp.Worker]WARNI|               __run: Execution of getTimestamp.12135.timestamp_update took too long: 1.16s
2019-12-16 14:42:53,089[             HABApp.Worker]WARNI|               __run: Execution of TVControl.update_received took too long: 1.02s
```
I did not get these previously (on the main branch), and none of these methods has anything in them that takes any time. None should take more than a few ms to execute.

eg: `LuxtoText()` is this:
```
    def item_state_update(self, event):
        self.log.debug('Item %s received update %s' % (event.name, event.value))
        if event.value is None:
            return
        for k,v in self.conversion_dict.items():
            if event.value <= v:
                text = k
                break
        else:
            text = 'Very Bright'
        
        self.log.info('%s lux(%s) set brightness level %s to: %s' % (event.name, event.value, self.text.name, text))
        self.oh.post_update(self.text, text)
```
where `self.conversion_dict` has 4 entries.
It seems like the `post_update` is taking too long. I have checked the VM processor load, and it's 7%, iowait 0.0%. No warnings in glances.

The messages seem to come in clusters, then nothing for a long time. I'll keep watching them, see if they correlate with any external events. The OH server HABApp is posting to is on the local VM using ip 127.0.0.1.

**Comment by spacemanspiff2007** [comment]
This is really strange - it's a default warning I have implemented when a func runs too long because if the user uses ````time.sleep```` a lot it may congest the worker.

But I don't see anything blocking here - ````post_update```` only adds the request to the event loop and that should be done in a couple of ms.

Maybe I should include a profiler and extend the error messages
