### ISSUE TITLE
self.__future_events.append(future_event) raising errors

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#97]
Recently I've been getting these error messages:
```
2019-12-17 17:19:43,017[             HABApp.Worker]ERROR|  __format_traceback: Error in TVControl.tv_lights_control: 'NoneType' object has no attribute 'append'
2019-12-17 17:19:43,018[             HABApp.Worker]ERROR|  __format_traceback: Traceback (most recent call last):
2019-12-17 17:19:43,021[             HABApp.Worker]ERROR|  __format_traceback:   File "/etc/openhab2/HABApp/lib/utils.py", line 391, in tv_lights_control
2019-12-17 17:19:43,022[             HABApp.Worker]ERROR|  __format_traceback:     self.set_tv_lights('ON')
2019-12-17 17:19:43,024[             HABApp.Worker]ERROR|  __format_traceback:   File "/etc/openhab2/HABApp/lib/utils.py", line 379, in set_tv_lights
2019-12-17 17:19:43,026[             HABApp.Worker]ERROR|  __format_traceback:     self.tv_lights_lockout['timer'].start()
2019-12-17 17:19:43,027[             HABApp.Worker]ERROR|  __format_traceback:   File "/etc/openhab2/HABApp/lib/utils.py", line 577, in start
2019-12-17 17:19:43,027[             HABApp.Worker]ERROR|  __format_traceback:     self._task = self.run_in(self.get_milliseconds, self.exec_func, *args, **kwargs)
2019-12-17 17:19:43,028[             HABApp.Worker]ERROR|  __format_traceback:   File "/home/nick/Scripts/HABApp/HABApp/rule/rule.py", line 372, in run_in
2019-12-17 17:19:43,028[             HABApp.Worker]ERROR|  __format_traceback:     self.__future_events.append(future_event)
2019-12-17 17:19:43,028[             HABApp.Worker]ERROR|  __format_traceback: AttributeError: 'NoneType' object has no attribute 'append'
```
not always on the same function, it varies. The error is always the same though.

I have tried the same action again that caused the error, but it subsequently works with no error.

This is after HABApp has been running for many hours with no errors, suddenly one of these error will occur, but when I repeat the action that caused the error, there is no error.

The above routine `tv_lights_control` is run when the TV is turned on or off. After I noticed the error, without changing anything I tried turning the TV on and off again, but no error occurred.

This is using the Dev branch of HABApp.

**Comment by spacemanspiff2007** [comment]
This is the result of a rule that already has been unloaded but is somehow kept in memory.
What's strange is that there are still things happening, because all event listeners should have been unloaded, too.
Do you keep any refs to the rule? Can you provide more context?

**Comment by NickWaterton** [comment]
I was thinking it was something like that.

This rule is a bit different, because `tv_lights_control` is in a file called `utils.py` which is in the `lib` directory (not the `rules` directory), part of a rule called `lights_tv_status`. This is because I actually use several functions from it in many different rules (eg the lighting is different depending on whether the TV is on or not). `utils.py` does not create an instance of the rule.

This rule does not change much, but because it's in `lib` it does not get unloaded and reloaded automatically if it's changed (I have to restart HABApp, so that all the files that use it re-import it).

The rule that calls it (in the `rules` directory) has an instance of `lights_tv_status` created when it initializes, and keeps that reference, so that it can call various methods like `tv_lights_control`.

I was thinking that if that reference became invalid, then every time I called something like `tv_lights_control` I would get an error, but I don't. This is what was confusing me. I get this error occasionally, not all the time. I could understand it if I had changed `utils.py` and forgot to restart HABApp, (as I am working on my rules actively).

So maybe I'm using the `lib` directory wrong, or maybe I'm not creating the instance of the rule in `utils.py` correctly.

Here is the snippet where it is instantiated

```
from utils import *

class TVControl(HABApp.Rule):
    '''
    TV Control
    '''
    
    watch_items =  ['TV_Skype_Incoming',
                    'TV_Skype_Status',
                    'Harmony_Starting',
                    'Harmony_Hub_Current_Activity']
    change_items = ['TV_HDMI_Select',
                    'TV_Power',
                    'TVON',
                    'virtualoutsidelight']
    command_item = ['TVPVR_Power']
    items =        ['Samsung_TV_Harmony_Send_ButtonPress',
                    'Raw_Send',
                    'TVSource_Name',
                    'TV_Skype_Last_Update',
                    'TVPowerOFF',
                    'iPad_Brightness',
                    'familyTVLamp',
                    'familyLamp',
                    'TV_Status',
                    'GC100Enabled']
                    
    create_items = ['harmony_tv',
                    'harmony_pvr',
                    'harmony_hub']
                    
    things =       ['samsungtv:tv:familyroom',
                    'globalcache:itachFlex:000C1E0372F3',
                    'harmonyhub:device:HarmonyHub:49046118',    #TV
                    'harmonyhub:device:HarmonyHub:5696225',     #PVR
                    'harmonyhub:device:HarmonyHub:']            #Hub
                    
    network_hdmi_command = {1 : 'HDMI1/DVI'}
    
    def __init__(self):
        super().__init__()
        self.log = logging.getLogger('MyRule.'+self.__class__.__name__)
        
        self.item = {}
        
        for item in self.watch_items:
            self.item[item] = Item.get_item(item)
            self.listen_event(self.item[item], self.update_received, ItemStateEvent)
            
        for item in self.change_items:
            self.item[item] = Item.get_item(item)
            self.listen_event(self.item[item], self.change_received, ItemStateChangedEvent)
            
        for item in self.command_item:
            self.item[item] = Item.get_item(item)
            self.listen_event(self.item[item], self.command_received, ItemCommandEvent)
            
        for item in self.items:
            self.item[item] = Item.get_item(item)
            
        for item in self.create_items:
            self.item[item] = Item.get_create_item(item)
            
        for thing in self.things:  
            self.listen_event(thing, self.thing_status_info, ThingStatusInfoEvent)
            self.listen_event(thing, self.thing_status_changed, ThingStatusInfoChangedEvent)
                                                        
        self.status = lights_tv_status()
```
The line `self.status = lights_tv_status()` is where the reference is created. The line that causes the error (sometimes) is:
```
        #allow time for harmony status to update
        self.run_in(1, self.status.tv_lights_control)
```
Am I doing something obviously wrong here?

**Comment by spacemanspiff2007** [comment]
I think the root cause is #123
